# Turkish lexemes common.py
lexemes = {
    "module_text_to_speech_name": "Metin okuma",
    "module_text_to_speech_action_read_selection": "Seçimi sesli oku",
    "module_text_to_speech_action_read_file": "Dosyayı sesli oku",
    "module_text_to_speech_action_read": "Sesli oku",
    "module_text_to_speech_action_read_document": "Belgeyi sesli oku",
    "module_text_to_speech_action_pause_resume": "Duraklat / Sürdür",
    "module_text_to_speech_action_stop": "Okumayı durdur",
    "module_text_to_speech_playback_details": "Oynatma ayrıntıları",
    "module_text_to_speech_model_not_loaded": "Yüklenmedi",
    "module_text_to_speech_playback_model": "Model: {value}",
    "module_text_to_speech_playback_codec": "Kodek modeli: {value}",
    "module_text_to_speech_playback_voice": "Ses: {value}",
    "module_text_to_speech_playback_language": "Dil: {value}",
    "module_text_to_speech_playback_sample_rate": "Örnekleme hızı: {value}",
    "module_text_to_speech_playback_rate": "Oynatma hızı: {value}",
    "module_text_to_speech_playback_audio_format": "Ses biçimi: PCM, 16 bit işaretli, mono",
    "module_text_to_speech_playback_speed": "Hız: {value}",
    "module_text_to_speech_playback_runtime": "Motor: {value}",
    "module_text_to_speech_dependency_required": "{value} gerekli",
    "module_text_to_speech_status_ready": "Okumaya hazır",
    "module_text_to_speech_status_stopped": "Durduruldu.",
    "module_text_to_speech_status_finished": "Okuma tamamlandı.",
    "module_text_to_speech_status_unavailable": "Konuşma kullanılamıyor.",
    "module_text_to_speech_status_empty": "Okunacak bir şey yok.",
    "module_text_to_speech_status_loading": "Konuşma modeli yükleniyor…",
    "module_text_to_speech_status_preparing": "Konuşma hazırlanıyor…",
    "module_text_to_speech_status_reading": "Sesli okunuyor…",
    "module_text_to_speech_status_paused": "Duraklatıldı.",
    "module_text_to_speech_error": "Hata: {error}",
    "module_text_to_speech_language_en": "İngilizce",
    "module_text_to_speech_language_es": "İspanyolca",
    "module_text_to_speech_language_de": "Almanca",
    "module_text_to_speech_language_fr": "Fransızca",
    "module_text_to_speech_language_it": "İtalyanca",
    "module_text_to_speech_language_vi": "Vietnamca",
    "module_text_to_speech_language_hi": "Hintçe",
    "module_text_to_speech_language_zh": "Çince (Mandarin)",
    "module_text_to_speech_language_ja": "Japonca",
    "module_text_to_speech_language_runtime_required": "motor desteği gerektirir",
    "module_text_to_speech_error_note_locked": "Sesli okumadan önce bu notu açıp kilidini kaldırın.",
    "module_text_to_speech_error_read_note": "Bu not okunamıyor: {error}",
    "module_text_to_speech_action_read_from_cursor": "İmleçten itibaren sesli oku",
}
