# Portuguese lexemes main_menu.py
lexemes = {
    "group_file_label": "Arquivo",
    "group_edit_label": "Editar",
    "group_tools_label": "Ferramentas",
    "group_help_label": "Ajuda",

    "actions_file_label_new_document": "Novo documento",
    "actions_file_accessible_name_new_document": "Novo documento",
    "actions_file_label_open": "Abrir",
    "actions_file_accessible_name_open": "Abrir documento",
    "actions_file_label_save": "Salvar",
    "actions_file_accessible_name_save": "Salvar documento",
    "actions_file_label_save_as": "Salvar como",
    "actions_file_accessible_name_save_as": "Salvar como cópia do documento",
    "actions_file_label_exit": "Sair do aplicativo",
    "actions_file_accessible_name_exit": "Sair do aplicativo",

    "edit_actions_edit_mode": "Editar",
    "edit_actions_accessible_name_edit_mode": "Editar arquivo",
    "edit_actions_source_mode": "Fonte",
    "edit_actions_accessible_name_source_mode": "Código-fonte",
    "edit_actions_bold": "Negrito",
    "edit_actions_accessible_name_bold": "Formato de texto em negrito",
    "edit_actions_italic": "Itálico",
    "edit_actions_accessible_name_italic": "Formato de texto em itálico",
    "edit_actions_underline": "Sublinhado",
    "edit_actions_accessible_name_underline": "Formato de texto sublinhado",
    "edit_actions_strikethrough": "Riscado",
    "edit_actions_accessible_name_strikethrough": "Formato de texto riscado",
    "edit_actions_blockquote": "Citação",
    "edit_actions_accessible_name_blockquote": "Formato de texto de citação",

    "tools_actions_ai_assistant": "Assistente de IA",
    "tools_actions_accessible_name_ai_assistant": "Lançar Assistente de IA",
    "tools_actions_color_picker": "Seletor de Cor",
    "tools_actions_accessible_name_color_picker": "Escolher uma cor para o texto",

    "actions_help_label_md_syntax": "Sintaxe Markdown",
    "actions_help_accessible_name_md_syntax": "Sintaxe Markdown",
    "actions_help_label_check_for_updates": "Verificar atualizações",
    "actions_help_accessible_name_check_for_updates": "Verificar atualizações",
    "actions_help_label_bug_report": "Relatar bug",
    "actions_help_accessible_name_bug_report": "Enviar relatório de bug",
    "actions_help_label_about": "Sobre",
    "actions_help_accessible_name_about": "Sobre",
}
