# Latin lexemes main_menu.py
lexemes = {
    "group_file_label": "Fasciculus",
    "group_edit_label": "Recensere",
    "group_tools_label": "Instrumenta",
    "group_help_label": "Auxilium",

    "actions_file_label_new_document": "Documentum novum",
    "actions_file_accessible_name_new_document": "Documentum novum",
    "actions_file_label_open": "Aperire",
    "actions_file_accessible_name_open": "Documentum aperire",
    "actions_file_label_save": "Servare",
    "actions_file_accessible_name_save": "Documentum Servare",
    "actions_file_label_save_as": "Salvare ut",
    "actions_file_accessible_name_save_as": "Salvare ut exemplar documenti",
    "actions_file_label_exit": "Excedere",
    "actions_file_accessible_name_exit": "Excedere applicationem",

    "edit_actions_edit_mode": "Recensere",
    "edit_actions_accessible_name_edit_mode": "Recensere fasciculum",
    "edit_actions_source_mode": "Fons",
    "edit_actions_accessible_name_source_mode": "Codex fontis",
    "edit_actions_bold": "Audax",
    "edit_actions_accessible_name_bold": "Formatum textus audacis",
    "edit_actions_italic": "Italicum",
    "edit_actions_accessible_name_italic": "Formatum textus italicum",
    "edit_actions_underline": "Sublineare",
    "edit_actions_accessible_name_underline": "Formatum textus sublinearis",
    "edit_actions_strikethrough": "Expungere",
    "edit_actions_accessible_name_strikethrough": "Formatum textus expungendi",
    "edit_actions_blockquote": "Blockquote",
    "edit_actions_accessible_name_blockquote": "Formatum textus blockquote",

    "tools_actions_ai_assistant": "Assistens AI",
    "tools_actions_accessible_name_ai_assistant": "Initiare Assistens AI",
    "tools_actions_color_picker": "Selector Coloris",
    "tools_actions_accessible_name_color_picker": "Eligere colorem textus",

    "actions_help_label_md_syntax": "Syntaxis markdown",
    "actions_help_accessible_name_md_syntax": "Syntaxis markdown",
    "actions_help_label_check_for_updates": "Repaginas scrutare",
    "actions_help_accessible_name_check_for_updates": "Repaginas scrutare",
    "actions_help_label_bug_report": "Falla nuntiare",
    "actions_help_accessible_name_bug_report": "Falla nuntiare",
    "actions_help_label_about": "De",
    "actions_help_accessible_name_about": "De",
}
