viewer_color_s=grey
viewer_color_todo=crimson
viewer_background_color_todo=lightPink

# Admonition colors
adm_note_color=0xFFFFFF
adm_info_color=0xFFFFFF
adm_tip_color=0xFFFFFF
adm_hint_color=0xFFFFFF
adm_warning_color=0xFFFFFF
adm_caution_color=0xFFFFFF
adm_danger_color=0xFFFFFF
adm_error_color=0xFFFFFF
adm_success_color=0xFFFFFF
adm_question_color=0xFFFFFF
adm_abstract_color=0xFFFFFF
adm_summary_color=0xFFFFFF
adm_example_color=0xFFFFFF
adm_bug_color=0xFFFFFF
adm_quote_color=0xFFFFFF
adm_failure_color=0xFFFFFF

adm_note_bg=0x4dd0e1
adm_info_bg=0x64b5f6
adm_tip_bg=0x81c784
adm_hint_bg=0x81c784
adm_warning_bg=0xffb74d
adm_caution_bg=0xffb74d
adm_danger_bg=0xe57373
adm_error_bg=0xe57373
adm_success_bg=0x66bb6a
adm_question_bg=0xba68c8
adm_abstract_bg=0x4fc3f7
adm_summary_bg=0x4fc3f7
adm_example_bg=0x9575cd
adm_bug_bg=0xf48fb1
adm_quote_bg=0x90a4ae
adm_failure_bg=0xef5350
