# French lexemes common.py
lexemes = {
    "module_text_to_speech_name": "Synthèse vocale",
    "module_text_to_speech_action_read_selection": "Lire la sélection à voix haute",
    "module_text_to_speech_action_read_file": "Lire le fichier à voix haute",
    "module_text_to_speech_action_read": "Lire à voix haute",
    "module_text_to_speech_action_read_document": "Lire le document à voix haute",
    "module_text_to_speech_action_pause_resume": "Pause / Reprendre",
    "module_text_to_speech_action_stop": "Arrêter la lecture",
    "module_text_to_speech_playback_details": "Détails de lecture",
    "module_text_to_speech_model_not_loaded": "Non chargé",
    "module_text_to_speech_playback_model": "Modèle : {value}",
    "module_text_to_speech_playback_codec": "Modèle de codec : {value}",
    "module_text_to_speech_playback_voice": "Voix : {value}",
    "module_text_to_speech_playback_language": "Langue : {value}",
    "module_text_to_speech_playback_sample_rate": "Fréquence d’échantillonnage : {value}",
    "module_text_to_speech_playback_rate": "Fréquence de lecture : {value}",
    "module_text_to_speech_playback_audio_format": "Format audio : PCM, 16 bits signés, mono",
    "module_text_to_speech_playback_speed": "Vitesse : {value}",
    "module_text_to_speech_playback_runtime": "Moteur : {value}",
    "module_text_to_speech_dependency_required": "{value} requis",
    "module_text_to_speech_status_ready": "Prêt à lire",
    "module_text_to_speech_status_stopped": "Arrêté.",
    "module_text_to_speech_status_finished": "Lecture terminée.",
    "module_text_to_speech_status_unavailable": "Synthèse vocale indisponible.",
    "module_text_to_speech_status_empty": "Rien à lire.",
    "module_text_to_speech_status_loading": "Chargement du modèle vocal…",
    "module_text_to_speech_status_preparing": "Préparation de la voix…",
    "module_text_to_speech_status_reading": "Lecture à voix haute…",
    "module_text_to_speech_status_paused": "En pause.",
    "module_text_to_speech_error": "Erreur : {error}",
    "module_text_to_speech_language_en": "Anglais",
    "module_text_to_speech_language_es": "Espagnol",
    "module_text_to_speech_language_de": "Allemand",
    "module_text_to_speech_language_fr": "Français",
    "module_text_to_speech_language_it": "Italien",
    "module_text_to_speech_language_vi": "Vietnamien",
    "module_text_to_speech_language_hi": "Hindi",
    "module_text_to_speech_language_zh": "Chinois (mandarin)",
    "module_text_to_speech_language_ja": "Japonais",
    "module_text_to_speech_language_runtime_required": "nécessite un moteur compatible",
    "module_text_to_speech_error_note_locked": "Ouvrez et déverrouillez cette note avant de la lire à voix haute.",
    "module_text_to_speech_error_read_note": "Impossible de lire cette note : {error}",
    "module_text_to_speech_action_read_from_cursor": "Lire à voix haute à partir du curseur",
}
