# Hindi lexemes common.py
lexemes = {
    "module_text_to_speech_name": "पाठ से वाणी",
    "module_text_to_speech_action_read_selection": "चयनित पाठ पढ़ें",
    "module_text_to_speech_action_read_file": "फ़ाइल पढ़ें",
    "module_text_to_speech_action_read": "ज़ोर से पढ़ें",
    "module_text_to_speech_action_read_document": "दस्तावेज़ पढ़ें",
    "module_text_to_speech_action_pause_resume": "विराम / जारी रखें",
    "module_text_to_speech_action_stop": "पढ़ना रोकें",
    "module_text_to_speech_playback_details": "प्लेबैक विवरण",
    "module_text_to_speech_model_not_loaded": "लोड नहीं हुआ",
    "module_text_to_speech_playback_model": "मॉडल: {value}",
    "module_text_to_speech_playback_codec": "कोडेक मॉडल: {value}",
    "module_text_to_speech_playback_voice": "आवाज़: {value}",
    "module_text_to_speech_playback_language": "भाषा: {value}",
    "module_text_to_speech_playback_sample_rate": "सैंपल दर: {value}",
    "module_text_to_speech_playback_rate": "प्लेबैक दर: {value}",
    "module_text_to_speech_playback_audio_format": "ऑडियो प्रारूप: PCM, 16-बिट साइन वाला, मोनो",
    "module_text_to_speech_playback_speed": "गति: {value}",
    "module_text_to_speech_playback_runtime": "रनटाइम: {value}",
    "module_text_to_speech_dependency_required": "{value} आवश्यक है",
    "module_text_to_speech_status_ready": "पढ़ने के लिए तैयार",
    "module_text_to_speech_status_stopped": "रोक दिया गया।",
    "module_text_to_speech_status_finished": "पढ़ना पूरा हुआ।",
    "module_text_to_speech_status_unavailable": "वाणी उपलब्ध नहीं है।",
    "module_text_to_speech_status_empty": "पढ़ने के लिए कुछ नहीं है।",
    "module_text_to_speech_status_loading": "वाणी मॉडल लोड हो रहा है…",
    "module_text_to_speech_status_preparing": "वाणी तैयार हो रही है…",
    "module_text_to_speech_status_reading": "पढ़ा जा रहा है…",
    "module_text_to_speech_status_paused": "विराम दिया गया।",
    "module_text_to_speech_error": "त्रुटि: {error}",
    "module_text_to_speech_language_en": "अंग्रेज़ी",
    "module_text_to_speech_language_es": "स्पेनिश",
    "module_text_to_speech_language_de": "जर्मन",
    "module_text_to_speech_language_fr": "फ़्रेंच",
    "module_text_to_speech_language_it": "इतालवी",
    "module_text_to_speech_language_vi": "वियतनामी",
    "module_text_to_speech_language_hi": "हिन्दी",
    "module_text_to_speech_language_zh": "चीनी (मंदारिन)",
    "module_text_to_speech_language_ja": "जापानी",
    "module_text_to_speech_language_runtime_required": "रनटाइम समर्थन आवश्यक",
    "module_text_to_speech_error_note_locked": "पढ़ने से पहले इस नोट को खोलें और अनलॉक करें।",
    "module_text_to_speech_error_read_note": "यह नोट नहीं पढ़ा जा सकता: {error}",
    "module_text_to_speech_action_read_from_cursor": "कर्सर से पढ़ना शुरू करें",
}
