# Greek lexemes common.py
lexemes = {
    "module_text_to_speech_name": "Κείμενο σε ομιλία",
    "module_text_to_speech_action_read_selection": "Εκφώνηση επιλογής",
    "module_text_to_speech_action_read_file": "Εκφώνηση αρχείου",
    "module_text_to_speech_action_read": "Εκφώνηση",
    "module_text_to_speech_action_read_document": "Εκφώνηση εγγράφου",
    "module_text_to_speech_action_pause_resume": "Παύση / Συνέχιση",
    "module_text_to_speech_action_stop": "Διακοπή ανάγνωσης",
    "module_text_to_speech_playback_details": "Στοιχεία αναπαραγωγής",
    "module_text_to_speech_model_not_loaded": "Δεν φορτώθηκε",
    "module_text_to_speech_playback_model": "Μοντέλο: {value}",
    "module_text_to_speech_playback_codec": "Μοντέλο κωδικοποιητή: {value}",
    "module_text_to_speech_playback_voice": "Φωνή: {value}",
    "module_text_to_speech_playback_language": "Γλώσσα: {value}",
    "module_text_to_speech_playback_sample_rate": "Ρυθμός δειγματοληψίας: {value}",
    "module_text_to_speech_playback_rate": "Ρυθμός αναπαραγωγής: {value}",
    "module_text_to_speech_playback_audio_format": "Μορφή ήχου: PCM, 16 bit με πρόσημο, μονοφωνικός",
    "module_text_to_speech_playback_speed": "Ταχύτητα: {value}",
    "module_text_to_speech_playback_runtime": "Μηχανή: {value}",
    "module_text_to_speech_dependency_required": "Απαιτείται {value}",
    "module_text_to_speech_status_ready": "Έτοιμο για ανάγνωση",
    "module_text_to_speech_status_stopped": "Διακόπηκε.",
    "module_text_to_speech_status_finished": "Η ανάγνωση ολοκληρώθηκε.",
    "module_text_to_speech_status_unavailable": "Η ομιλία δεν είναι διαθέσιμη.",
    "module_text_to_speech_status_empty": "Δεν υπάρχει κείμενο για ανάγνωση.",
    "module_text_to_speech_status_loading": "Φόρτωση μοντέλου ομιλίας…",
    "module_text_to_speech_status_preparing": "Προετοιμασία ομιλίας…",
    "module_text_to_speech_status_reading": "Εκφώνηση…",
    "module_text_to_speech_status_paused": "Σε παύση.",
    "module_text_to_speech_error": "Σφάλμα: {error}",
    "module_text_to_speech_language_en": "Αγγλικά",
    "module_text_to_speech_language_es": "Ισπανικά",
    "module_text_to_speech_language_de": "Γερμανικά",
    "module_text_to_speech_language_fr": "Γαλλικά",
    "module_text_to_speech_language_it": "Ιταλικά",
    "module_text_to_speech_language_vi": "Βιετναμικά",
    "module_text_to_speech_language_hi": "Χίντι",
    "module_text_to_speech_language_zh": "Κινεζικά (μανδαρινικά)",
    "module_text_to_speech_language_ja": "Ιαπωνικά",
    "module_text_to_speech_language_runtime_required": "απαιτεί υποστήριξη μηχανής",
    "module_text_to_speech_error_note_locked": "Ανοίξτε και ξεκλειδώστε τη σημείωση πριν την εκφώνηση.",
    "module_text_to_speech_error_read_note": "Δεν είναι δυνατή η ανάγνωση της σημείωσης: {error}",
    "module_text_to_speech_action_read_from_cursor": "Εκφώνηση από τον δρομέα",
}
