# Dutch lexemes common.py
lexemes = {
    "module_text_to_speech_name": "Tekst-naar-spraak",
    "module_text_to_speech_action_read_selection": "Selectie voorlezen",
    "module_text_to_speech_action_read_file": "Bestand voorlezen",
    "module_text_to_speech_action_read": "Voorlezen",
    "module_text_to_speech_action_read_document": "Document voorlezen",
    "module_text_to_speech_action_pause_resume": "Pauzeren / Hervatten",
    "module_text_to_speech_action_stop": "Voorlezen stoppen",
    "module_text_to_speech_playback_details": "Afspeeldetails",
    "module_text_to_speech_model_not_loaded": "Niet geladen",
    "module_text_to_speech_playback_model": "Model: {value}",
    "module_text_to_speech_playback_codec": "Codecmodel: {value}",
    "module_text_to_speech_playback_voice": "Stem: {value}",
    "module_text_to_speech_playback_language": "Taal: {value}",
    "module_text_to_speech_playback_sample_rate": "Samplefrequentie: {value}",
    "module_text_to_speech_playback_rate": "Afspeelfrequentie: {value}",
    "module_text_to_speech_playback_audio_format": "Audioformaat: PCM, 16-bit met teken, mono",
    "module_text_to_speech_playback_speed": "Snelheid: {value}",
    "module_text_to_speech_playback_runtime": "Runtime: {value}",
    "module_text_to_speech_dependency_required": "{value} vereist",
    "module_text_to_speech_status_ready": "Klaar om voor te lezen",
    "module_text_to_speech_status_stopped": "Gestopt.",
    "module_text_to_speech_status_finished": "Voorlezen voltooid.",
    "module_text_to_speech_status_unavailable": "Spraak niet beschikbaar.",
    "module_text_to_speech_status_empty": "Niets om voor te lezen.",
    "module_text_to_speech_status_loading": "Spraakmodel laden…",
    "module_text_to_speech_status_preparing": "Spraak voorbereiden…",
    "module_text_to_speech_status_reading": "Voorlezen…",
    "module_text_to_speech_status_paused": "Gepauzeerd.",
    "module_text_to_speech_error": "Fout: {error}",
    "module_text_to_speech_language_en": "Engels",
    "module_text_to_speech_language_es": "Spaans",
    "module_text_to_speech_language_de": "Duits",
    "module_text_to_speech_language_fr": "Frans",
    "module_text_to_speech_language_it": "Italiaans",
    "module_text_to_speech_language_vi": "Vietnamees",
    "module_text_to_speech_language_hi": "Hindi",
    "module_text_to_speech_language_zh": "Chinees (Mandarijn)",
    "module_text_to_speech_language_ja": "Japans",
    "module_text_to_speech_language_runtime_required": "runtimeondersteuning vereist",
    "module_text_to_speech_error_note_locked": "Open en ontgrendel deze notitie voordat u die laat voorlezen.",
    "module_text_to_speech_error_read_note": "Deze notitie kan niet worden gelezen: {error}",
    "module_text_to_speech_action_read_from_cursor": "Vanaf cursor voorlezen",
}
