# Russian lexemes common.py
lexemes = {
    "module_text_to_speech_name": "Озвучивание текста",
    "module_text_to_speech_action_read_selection": "Прочитать выделенное вслух",
    "module_text_to_speech_action_read_file": "Прочитать файл вслух",
    "module_text_to_speech_action_read": "Прочитать вслух",
    "module_text_to_speech_action_read_document": "Прочитать документ вслух",
    "module_text_to_speech_action_pause_resume": "Пауза / Продолжить",
    "module_text_to_speech_action_stop": "Остановить чтение",
    "module_text_to_speech_playback_details": "Сведения о воспроизведении",
    "module_text_to_speech_model_not_loaded": "Не загружено",
    "module_text_to_speech_playback_model": "Модель: {value}",
    "module_text_to_speech_playback_codec": "Модель кодека: {value}",
    "module_text_to_speech_playback_voice": "Голос: {value}",
    "module_text_to_speech_playback_language": "Язык: {value}",
    "module_text_to_speech_playback_sample_rate": "Частота дискретизации: {value}",
    "module_text_to_speech_playback_rate": "Частота воспроизведения: {value}",
    "module_text_to_speech_playback_audio_format": "Формат аудио: PCM, 16 бит со знаком, моно",
    "module_text_to_speech_playback_speed": "Скорость: {value}",
    "module_text_to_speech_playback_runtime": "Движок: {value}",
    "module_text_to_speech_dependency_required": "Требуется {value}",
    "module_text_to_speech_status_ready": "Готово к чтению",
    "module_text_to_speech_status_stopped": "Остановлено.",
    "module_text_to_speech_status_finished": "Чтение завершено.",
    "module_text_to_speech_status_unavailable": "Озвучивание недоступно.",
    "module_text_to_speech_status_empty": "Нет текста для чтения.",
    "module_text_to_speech_status_loading": "Загрузка речевой модели…",
    "module_text_to_speech_status_preparing": "Подготовка речи…",
    "module_text_to_speech_status_reading": "Чтение вслух…",
    "module_text_to_speech_status_paused": "Пауза.",
    "module_text_to_speech_error": "Ошибка: {error}",
    "module_text_to_speech_language_en": "Английский",
    "module_text_to_speech_language_es": "Испанский",
    "module_text_to_speech_language_de": "Немецкий",
    "module_text_to_speech_language_fr": "Французский",
    "module_text_to_speech_language_it": "Итальянский",
    "module_text_to_speech_language_vi": "Вьетнамский",
    "module_text_to_speech_language_hi": "Хинди",
    "module_text_to_speech_language_zh": "Китайский (мандаринский)",
    "module_text_to_speech_language_ja": "Японский",
    "module_text_to_speech_language_runtime_required": "нужна поддержка движка",
    "module_text_to_speech_error_note_locked": "Откройте и разблокируйте заметку перед чтением вслух.",
    "module_text_to_speech_error_read_note": "Не удалось прочитать заметку: {error}",
    "module_text_to_speech_action_read_from_cursor": "Прочитать вслух от курсора",
}
