# German lexemes common.py
lexemes = {
    "module_text_to_speech_name": "Text zu Sprache",
    "module_text_to_speech_action_read_selection": "Auswahl vorlesen",
    "module_text_to_speech_action_read_file": "Datei vorlesen",
    "module_text_to_speech_action_read": "Vorlesen",
    "module_text_to_speech_action_read_document": "Dokument vorlesen",
    "module_text_to_speech_action_pause_resume": "Pause / Fortsetzen",
    "module_text_to_speech_action_stop": "Vorlesen beenden",
    "module_text_to_speech_playback_details": "Wiedergabedetails",
    "module_text_to_speech_model_not_loaded": "Nicht geladen",
    "module_text_to_speech_playback_model": "Modell: {value}",
    "module_text_to_speech_playback_codec": "Codec-Modell: {value}",
    "module_text_to_speech_playback_voice": "Stimme: {value}",
    "module_text_to_speech_playback_language": "Sprache: {value}",
    "module_text_to_speech_playback_sample_rate": "Abtastrate: {value}",
    "module_text_to_speech_playback_rate": "Wiedergaberate: {value}",
    "module_text_to_speech_playback_audio_format": "Audioformat: PCM, 16 Bit mit Vorzeichen, Mono",
    "module_text_to_speech_playback_speed": "Geschwindigkeit: {value}",
    "module_text_to_speech_playback_runtime": "Laufzeit: {value}",
    "module_text_to_speech_dependency_required": "{value} erforderlich",
    "module_text_to_speech_status_ready": "Bereit zum Vorlesen",
    "module_text_to_speech_status_stopped": "Gestoppt.",
    "module_text_to_speech_status_finished": "Vorlesen beendet.",
    "module_text_to_speech_status_unavailable": "Sprachausgabe nicht verfügbar.",
    "module_text_to_speech_status_empty": "Nichts vorzulesen.",
    "module_text_to_speech_status_loading": "Sprachmodell wird geladen…",
    "module_text_to_speech_status_preparing": "Sprachausgabe wird vorbereitet…",
    "module_text_to_speech_status_reading": "Wird vorgelesen…",
    "module_text_to_speech_status_paused": "Pausiert.",
    "module_text_to_speech_error": "Fehler: {error}",
    "module_text_to_speech_language_en": "Englisch",
    "module_text_to_speech_language_es": "Spanisch",
    "module_text_to_speech_language_de": "Deutsch",
    "module_text_to_speech_language_fr": "Französisch",
    "module_text_to_speech_language_it": "Italienisch",
    "module_text_to_speech_language_vi": "Vietnamesisch",
    "module_text_to_speech_language_hi": "Hindi",
    "module_text_to_speech_language_zh": "Chinesisch (Mandarin)",
    "module_text_to_speech_language_ja": "Japanisch",
    "module_text_to_speech_language_runtime_required": "Laufzeitunterstützung erforderlich",
    "module_text_to_speech_error_note_locked": "Öffnen und entsperren Sie die Notiz vor dem Vorlesen.",
    "module_text_to_speech_error_read_note": "Diese Notiz kann nicht gelesen werden: {error}",
    "module_text_to_speech_action_read_from_cursor": "Ab Cursor vorlesen",
}
