# Swedish lexemes common.py
lexemes = {
    "module_text_to_speech_name": "Text till tal",
    "module_text_to_speech_action_read_selection": "Läs markering högt",
    "module_text_to_speech_action_read_file": "Läs fil högt",
    "module_text_to_speech_action_read": "Läs högt",
    "module_text_to_speech_action_read_document": "Läs dokument högt",
    "module_text_to_speech_action_pause_resume": "Pausa / Fortsätt",
    "module_text_to_speech_action_stop": "Stoppa läsning",
    "module_text_to_speech_playback_details": "Uppspelningsdetaljer",
    "module_text_to_speech_model_not_loaded": "Inte inläst",
    "module_text_to_speech_playback_model": "Modell: {value}",
    "module_text_to_speech_playback_codec": "Kodekmodell: {value}",
    "module_text_to_speech_playback_voice": "Röst: {value}",
    "module_text_to_speech_playback_language": "Språk: {value}",
    "module_text_to_speech_playback_sample_rate": "Samplingsfrekvens: {value}",
    "module_text_to_speech_playback_rate": "Uppspelningsfrekvens: {value}",
    "module_text_to_speech_playback_audio_format": "Ljudformat: PCM, 16 bitar med tecken, mono",
    "module_text_to_speech_playback_speed": "Hastighet: {value}",
    "module_text_to_speech_playback_runtime": "Motor: {value}",
    "module_text_to_speech_dependency_required": "{value} krävs",
    "module_text_to_speech_status_ready": "Redo att läsa",
    "module_text_to_speech_status_stopped": "Stoppad.",
    "module_text_to_speech_status_finished": "Läsningen klar.",
    "module_text_to_speech_status_unavailable": "Tal är inte tillgängligt.",
    "module_text_to_speech_status_empty": "Inget att läsa.",
    "module_text_to_speech_status_loading": "Läser in talmodell…",
    "module_text_to_speech_status_preparing": "Förbereder tal…",
    "module_text_to_speech_status_reading": "Läser högt…",
    "module_text_to_speech_status_paused": "Pausad.",
    "module_text_to_speech_error": "Fel: {error}",
    "module_text_to_speech_language_en": "Engelska",
    "module_text_to_speech_language_es": "Spanska",
    "module_text_to_speech_language_de": "Tyska",
    "module_text_to_speech_language_fr": "Franska",
    "module_text_to_speech_language_it": "Italienska",
    "module_text_to_speech_language_vi": "Vietnamesiska",
    "module_text_to_speech_language_hi": "Hindi",
    "module_text_to_speech_language_zh": "Kinesiska (mandarin)",
    "module_text_to_speech_language_ja": "Japanska",
    "module_text_to_speech_language_runtime_required": "kräver motorstöd",
    "module_text_to_speech_error_note_locked": "Öppna och lås upp anteckningen innan den läses högt.",
    "module_text_to_speech_error_read_note": "Anteckningen kan inte läsas: {error}",
    "module_text_to_speech_action_read_from_cursor": "Läs högt från markören",
}
