# Finnish lexemes common.py
lexemes = {
    "module_text_to_speech_name": "Teksti puheeksi",
    "module_text_to_speech_action_read_selection": "Lue valinta ääneen",
    "module_text_to_speech_action_read_file": "Lue tiedosto ääneen",
    "module_text_to_speech_action_read": "Lue ääneen",
    "module_text_to_speech_action_read_document": "Lue asiakirja ääneen",
    "module_text_to_speech_action_pause_resume": "Tauko / Jatka",
    "module_text_to_speech_action_stop": "Lopeta lukeminen",
    "module_text_to_speech_playback_details": "Toiston tiedot",
    "module_text_to_speech_model_not_loaded": "Ei ladattu",
    "module_text_to_speech_playback_model": "Malli: {value}",
    "module_text_to_speech_playback_codec": "Koodekkimalli: {value}",
    "module_text_to_speech_playback_voice": "Ääni: {value}",
    "module_text_to_speech_playback_language": "Kieli: {value}",
    "module_text_to_speech_playback_sample_rate": "Näytteenottotaajuus: {value}",
    "module_text_to_speech_playback_rate": "Toistotaajuus: {value}",
    "module_text_to_speech_playback_audio_format": "Äänimuoto: PCM, 16-bittinen etumerkillinen, mono",
    "module_text_to_speech_playback_speed": "Nopeus: {value}",
    "module_text_to_speech_playback_runtime": "Moottori: {value}",
    "module_text_to_speech_dependency_required": "{value} tarvitaan",
    "module_text_to_speech_status_ready": "Valmis lukemaan",
    "module_text_to_speech_status_stopped": "Pysäytetty.",
    "module_text_to_speech_status_finished": "Lukeminen valmis.",
    "module_text_to_speech_status_unavailable": "Puhe ei ole käytettävissä.",
    "module_text_to_speech_status_empty": "Ei luettavaa.",
    "module_text_to_speech_status_loading": "Ladataan puhemallia…",
    "module_text_to_speech_status_preparing": "Valmistellaan puhetta…",
    "module_text_to_speech_status_reading": "Luetaan ääneen…",
    "module_text_to_speech_status_paused": "Tauolla.",
    "module_text_to_speech_error": "Virhe: {error}",
    "module_text_to_speech_language_en": "Englanti",
    "module_text_to_speech_language_es": "Espanja",
    "module_text_to_speech_language_de": "Saksa",
    "module_text_to_speech_language_fr": "Ranska",
    "module_text_to_speech_language_it": "Italia",
    "module_text_to_speech_language_vi": "Vietnam",
    "module_text_to_speech_language_hi": "Hindi",
    "module_text_to_speech_language_zh": "Kiina (mandariini)",
    "module_text_to_speech_language_ja": "Japani",
    "module_text_to_speech_language_runtime_required": "vaatii moottorin tuen",
    "module_text_to_speech_error_note_locked": "Avaa tämä muistiinpano ja poista lukitus ennen ääneen lukemista.",
    "module_text_to_speech_error_read_note": "Muistiinpanoa ei voi lukea: {error}",
    "module_text_to_speech_action_read_from_cursor": "Lue ääneen kohdistimesta alkaen",
}
