name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear description of the feature you'd like
      placeholder: What would you like to see added?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this feature be useful?
      placeholder: What problem does this solve?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've considered?

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      options:
        - Editor / Markdown
        - Viewer / Rendering
        - AI Assistant
        - File Management
        - Encryption / Security
        - UI / Themes
        - Translations / i18n
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any mockups, examples, or additional information
