# Latin lexemes common.py
lexemes = {
    "module_text_to_speech_name": "Textus in vocem",
    "module_text_to_speech_action_read_selection": "Selectionem recita",
    "module_text_to_speech_action_read_file": "Documentum recita",
    "module_text_to_speech_action_read": "Recita",
    "module_text_to_speech_action_read_document": "Textum totum recita",
    "module_text_to_speech_action_pause_resume": "Intermitte / Perge",
    "module_text_to_speech_action_stop": "Lectionem siste",
    "module_text_to_speech_playback_details": "Singula soni",
    "module_text_to_speech_model_not_loaded": "Nondum oneratum",
    "module_text_to_speech_playback_model": "Exemplar: {value}",
    "module_text_to_speech_playback_codec": "Exemplar codec: {value}",
    "module_text_to_speech_playback_voice": "Vox: {value}",
    "module_text_to_speech_playback_language": "Lingua: {value}",
    "module_text_to_speech_playback_sample_rate": "Frequentia exemplorum: {value}",
    "module_text_to_speech_playback_rate": "Frequentia soni: {value}",
    "module_text_to_speech_playback_audio_format": "Forma soni: PCM, 16 bit cum signo, mono",
    "module_text_to_speech_playback_speed": "Celeritas: {value}",
    "module_text_to_speech_playback_runtime": "Machina: {value}",
    "module_text_to_speech_dependency_required": "{value} requiritur",
    "module_text_to_speech_status_ready": "Ad legendum paratum",
    "module_text_to_speech_status_stopped": "Sistitur.",
    "module_text_to_speech_status_finished": "Lectio finita.",
    "module_text_to_speech_status_unavailable": "Vox non praesto est.",
    "module_text_to_speech_status_empty": "Nihil legendum.",
    "module_text_to_speech_status_loading": "Exemplar vocale oneratur…",
    "module_text_to_speech_status_preparing": "Vox paratur…",
    "module_text_to_speech_status_reading": "Recitatur…",
    "module_text_to_speech_status_paused": "Intermissum.",
    "module_text_to_speech_error": "Error: {error}",
    "module_text_to_speech_language_en": "Anglica",
    "module_text_to_speech_language_es": "Hispanica",
    "module_text_to_speech_language_de": "Germanica",
    "module_text_to_speech_language_fr": "Francogallica",
    "module_text_to_speech_language_it": "Italica",
    "module_text_to_speech_language_vi": "Vietnamica",
    "module_text_to_speech_language_hi": "Hindi",
    "module_text_to_speech_language_zh": "Sinica (Mandarinica)",
    "module_text_to_speech_language_ja": "Iaponica",
    "module_text_to_speech_language_runtime_required": "machina idonea requiritur",
    "module_text_to_speech_error_note_locked": "Hanc notam aperi et resera ante recitationem.",
    "module_text_to_speech_error_read_note": "Haec nota legi non potest: {error}",
    "module_text_to_speech_action_read_from_cursor": "A cursore recita",
}
