# Georgian lexemes common.py
lexemes = {
    "module_text_to_speech_name": "ტექსტის გახმოვანება",
    "module_text_to_speech_action_read_selection": "მონიშნულის ხმამაღლა წაკითხვა",
    "module_text_to_speech_action_read_file": "ფაილის ხმამაღლა წაკითხვა",
    "module_text_to_speech_action_read": "ხმამაღლა წაკითხვა",
    "module_text_to_speech_action_read_document": "დოკუმენტის ხმამაღლა წაკითხვა",
    "module_text_to_speech_action_pause_resume": "პაუზა / გაგრძელება",
    "module_text_to_speech_action_stop": "კითხვის შეჩერება",
    "module_text_to_speech_playback_details": "დაკვრის დეტალები",
    "module_text_to_speech_model_not_loaded": "არ არის ჩატვირთული",
    "module_text_to_speech_playback_model": "მოდელი: {value}",
    "module_text_to_speech_playback_codec": "კოდეკის მოდელი: {value}",
    "module_text_to_speech_playback_voice": "ხმა: {value}",
    "module_text_to_speech_playback_language": "ენა: {value}",
    "module_text_to_speech_playback_sample_rate": "დისკრეტიზაციის სიხშირე: {value}",
    "module_text_to_speech_playback_rate": "დაკვრის სიხშირე: {value}",
    "module_text_to_speech_playback_audio_format": "აუდიოფორმატი: PCM, 16-ბიტიანი ნიშნით, მონო",
    "module_text_to_speech_playback_speed": "სიჩქარე: {value}",
    "module_text_to_speech_playback_runtime": "ძრავა: {value}",
    "module_text_to_speech_dependency_required": "საჭიროა {value}",
    "module_text_to_speech_status_ready": "მზადაა წასაკითხად",
    "module_text_to_speech_status_stopped": "შეჩერებულია.",
    "module_text_to_speech_status_finished": "კითხვა დასრულდა.",
    "module_text_to_speech_status_unavailable": "მეტყველება მიუწვდომელია.",
    "module_text_to_speech_status_empty": "წასაკითხი ტექსტი არ არის.",
    "module_text_to_speech_status_loading": "მეტყველების მოდელი იტვირთება…",
    "module_text_to_speech_status_preparing": "მეტყველება მზადდება…",
    "module_text_to_speech_status_reading": "ხმამაღლა იკითხება…",
    "module_text_to_speech_status_paused": "დაპაუზებულია.",
    "module_text_to_speech_error": "შეცდომა: {error}",
    "module_text_to_speech_language_en": "ინგლისური",
    "module_text_to_speech_language_es": "ესპანური",
    "module_text_to_speech_language_de": "გერმანული",
    "module_text_to_speech_language_fr": "ფრანგული",
    "module_text_to_speech_language_it": "იტალიური",
    "module_text_to_speech_language_vi": "ვიეტნამური",
    "module_text_to_speech_language_hi": "ჰინდი",
    "module_text_to_speech_language_zh": "ჩინური (მანდარინული)",
    "module_text_to_speech_language_ja": "იაპონური",
    "module_text_to_speech_language_runtime_required": "საჭიროა ძრავის მხარდაჭერა",
    "module_text_to_speech_error_note_locked": "ხმამაღლა წაკითხვამდე გახსენით და განბლოკეთ ეს ჩანაწერი.",
    "module_text_to_speech_error_read_note": "ჩანაწერის წაკითხვა ვერ მოხერხდა: {error}",
    "module_text_to_speech_action_read_from_cursor": "კურსორიდან ხმამაღლა წაკითხვა",
}
