# English lexemes common.py
lexemes = {
    "module_text_to_speech_name": "Text-to-Speech",
    "module_text_to_speech_action_read_selection": "Read selection aloud",
    "module_text_to_speech_action_read_file": "Read file aloud",
    "module_text_to_speech_action_read": "Read aloud",
    "module_text_to_speech_action_read_document": "Read document aloud",
    "module_text_to_speech_action_pause_resume": "Pause / resume",
    "module_text_to_speech_action_stop": "Stop reading",
    "module_text_to_speech_playback_details": "Speech playback details",
    "module_text_to_speech_model_not_loaded": "Not loaded",
    "module_text_to_speech_playback_model": "Model: {value}",
    "module_text_to_speech_playback_codec": "Codec model: {value}",
    "module_text_to_speech_playback_voice": "Voice: {value}",
    "module_text_to_speech_playback_language": "Language: {value}",
    "module_text_to_speech_playback_sample_rate": "Sample rate: {value}",
    "module_text_to_speech_playback_rate": "Playback rate: {value}",
    "module_text_to_speech_playback_audio_format": "Audio format: PCM, 16-bit signed, mono",
    "module_text_to_speech_playback_speed": "Speed: {value}",
    "module_text_to_speech_playback_runtime": "Runtime: {value}",
    "module_text_to_speech_dependency_required": "{value} required",
    "module_text_to_speech_status_ready": "Ready to read",
    "module_text_to_speech_status_stopped": "Stopped.",
    "module_text_to_speech_status_finished": "Finished reading.",
    "module_text_to_speech_status_unavailable": "Speech unavailable.",
    "module_text_to_speech_status_empty": "Nothing to read.",
    "module_text_to_speech_status_loading": "Loading speech model…",
    "module_text_to_speech_status_preparing": "Preparing speech…",
    "module_text_to_speech_status_reading": "Reading aloud…",
    "module_text_to_speech_status_paused": "Paused.",
    "module_text_to_speech_error": "Error: {error}",
    "module_text_to_speech_language_en": "English",
    "module_text_to_speech_language_es": "Spanish",
    "module_text_to_speech_language_de": "German",
    "module_text_to_speech_language_fr": "French",
    "module_text_to_speech_language_it": "Italian",
    "module_text_to_speech_language_vi": "Vietnamese",
    "module_text_to_speech_language_hi": "Hindi",
    "module_text_to_speech_language_zh": "Chinese (Mandarin)",
    "module_text_to_speech_language_ja": "Japanese",
    "module_text_to_speech_language_runtime_required": "requires runtime support",
    "module_text_to_speech_error_note_locked": "Open and unlock this note before reading it aloud.",
    "module_text_to_speech_error_read_note": "Cannot read this note: {error}",
    "module_text_to_speech_action_read_from_cursor": "Read from cursor aloud",
}
