# Indonesian lexemes common.py
lexemes = {
    "module_text_to_speech_name": "Teks ke Ucapan",
    "module_text_to_speech_action_read_selection": "Bacakan pilihan",
    "module_text_to_speech_action_read_file": "Bacakan file",
    "module_text_to_speech_action_read": "Bacakan",
    "module_text_to_speech_action_read_document": "Bacakan dokumen",
    "module_text_to_speech_action_pause_resume": "Jeda / Lanjutkan",
    "module_text_to_speech_action_stop": "Hentikan pembacaan",
    "module_text_to_speech_playback_details": "Detail pemutaran",
    "module_text_to_speech_model_not_loaded": "Belum dimuat",
    "module_text_to_speech_playback_model": "Model: {value}",
    "module_text_to_speech_playback_codec": "Model kodek: {value}",
    "module_text_to_speech_playback_voice": "Suara: {value}",
    "module_text_to_speech_playback_language": "Bahasa: {value}",
    "module_text_to_speech_playback_sample_rate": "Laju sampel: {value}",
    "module_text_to_speech_playback_rate": "Laju pemutaran: {value}",
    "module_text_to_speech_playback_audio_format": "Format audio: PCM, 16-bit bertanda, mono",
    "module_text_to_speech_playback_speed": "Kecepatan: {value}",
    "module_text_to_speech_playback_runtime": "Mesin: {value}",
    "module_text_to_speech_dependency_required": "Memerlukan {value}",
    "module_text_to_speech_status_ready": "Siap membaca",
    "module_text_to_speech_status_stopped": "Dihentikan.",
    "module_text_to_speech_status_finished": "Pembacaan selesai.",
    "module_text_to_speech_status_unavailable": "Ucapan tidak tersedia.",
    "module_text_to_speech_status_empty": "Tidak ada yang dibaca.",
    "module_text_to_speech_status_loading": "Memuat model ucapan…",
    "module_text_to_speech_status_preparing": "Menyiapkan ucapan…",
    "module_text_to_speech_status_reading": "Membacakan…",
    "module_text_to_speech_status_paused": "Dijeda.",
    "module_text_to_speech_error": "Kesalahan: {error}",
    "module_text_to_speech_language_en": "Inggris",
    "module_text_to_speech_language_es": "Spanyol",
    "module_text_to_speech_language_de": "Jerman",
    "module_text_to_speech_language_fr": "Prancis",
    "module_text_to_speech_language_it": "Italia",
    "module_text_to_speech_language_vi": "Vietnam",
    "module_text_to_speech_language_hi": "Hindi",
    "module_text_to_speech_language_zh": "Tionghoa (Mandarin)",
    "module_text_to_speech_language_ja": "Jepang",
    "module_text_to_speech_language_runtime_required": "memerlukan dukungan mesin",
    "module_text_to_speech_error_note_locked": "Buka dan buka kunci catatan ini sebelum membacakannya.",
    "module_text_to_speech_error_read_note": "Catatan ini tidak dapat dibaca: {error}",
    "module_text_to_speech_action_read_from_cursor": "Bacakan mulai dari kursor",
}
