# Indonesian lexemes color_picker_dialog.py
lexemes = {
    "color_picker_title": "Pilih Warna",

    "color_picker_color_black": "Hitam",
    "color_picker_color_silver": "Perak",
    "color_picker_color_gray": "Abu-abu",
    "color_picker_color_white": "Putih",
    "color_picker_color_maroon": "Merah Marun",
    "color_picker_color_red": "Merah",
    "color_picker_color_purple": "Ungu",
    "color_picker_color_fuchsia": "Fuchsia",
    "color_picker_color_green": "Hijau",
    "color_picker_color_lime": "Limau",
    "color_picker_color_olive": "Zaitun",
    "color_picker_color_yellow": "Kuning",
    "color_picker_color_navy": "Biru Dongker",
    "color_picker_color_blue": "Biru",
    "color_picker_color_teal": "Teal",
    "color_picker_color_aqua": "Aqua",
    "color_picker_color_aliceblue": "Biru Alice",
    "color_picker_color_antiquewhite": "Putih Antik",
    "color_picker_color_aquamarine": "Aquamarine",
    "color_picker_color_azure": "Biru Langit",
    "color_picker_color_beige": "Krem",
    "color_picker_color_bisque": "Bisque",
    "color_picker_color_blanchedalmond": "Almond Pucat",
    "color_picker_color_blueviolet": "Biru Violet",
    "color_picker_color_brown": "Cokelat",
    "color_picker_color_burlywood": "Kayu Burly",
    "color_picker_color_cadetblue": "Biru Kadet",
    "color_picker_color_chartreuse": "Chartreuse",
    "color_picker_color_chocolate": "Cokelat Tua",
    "color_picker_color_coral": "Koral",
    "color_picker_color_cornflowerblue": "Biru Bunga Jagung",
    "color_picker_color_cornsilk": "Sutra Jagung",
    "color_picker_color_crimson": "Merah Tua",
    "color_picker_color_cyan": "Sian",
    "color_picker_color_darkblue": "Biru Gelap",
    "color_picker_color_darkcyan": "Sian Gelap",
    "color_picker_color_darkgoldenrod": "Emas Gelap",
    "color_picker_color_darkgray": "Abu-abu Gelap",
    "color_picker_color_darkgreen": "Hijau Gelap",
    "color_picker_color_darkkhaki": "Khaki Gelap",
    "color_picker_color_darkmagenta": "Magenta Gelap",
    "color_picker_color_darkolivegreen": "Hijau Zaitun Gelap",
    "color_picker_color_darkorange": "Oranye Gelap",
    "color_picker_color_darkorchid": "Anggrek Gelap",
    "color_picker_color_darkred": "Merah Gelap",
    "color_picker_color_darksalmon": "Salmon Gelap",
    "color_picker_color_darkseagreen": "Hijau Laut Gelap",
    "color_picker_color_darkslateblue": "Biru Batu Tulis Gelap",
    "color_picker_color_darkslategray": "Abu-abu Batu Tulis Gelap",
    "color_picker_color_darkturquoise": "Toska Gelap",
    "color_picker_color_darkviolet": "Violet Gelap",
    "color_picker_color_deeppink": "Merah Muda Pekat",
    "color_picker_color_deepskyblue": "Biru Langit Pekat",
    "color_picker_color_dimgray": "Abu-abu Redup",
    "color_picker_color_dodgerblue": "Biru Dodger",
    "color_picker_color_firebrick": "Bata Api",
    "color_picker_color_floralwhite": "Putih Bunga",
    "color_picker_color_forestgreen": "Hijau Hutan",
    "color_picker_color_gainsboro": "Gainsboro",
    "color_picker_color_ghostwhite": "Putih Hantu",
    "color_picker_color_gold": "Emas",
    "color_picker_color_goldenrod": "Batang Emas",
    "color_picker_color_greenyellow": "Hijau Kuning",
    "color_picker_color_honeydew": "Embun Madu",
    "color_picker_color_hotpink": "Merah Muda Panas",
    "color_picker_color_indianred": "Merah India",
    "color_picker_color_indigo": "Nila",
    "color_picker_color_ivory": "Gading",
    "color_picker_color_khaki": "Khaki",
    "color_picker_color_lavender": "Lavender",
    "color_picker_color_lavenderblush": "Lavender Merona",
    "color_picker_color_lawngreen": "Hijau Rumput",
    "color_picker_color_lemonchiffon": "Sifon Lemon",
    "color_picker_color_lightblue": "Biru Muda",
    "color_picker_color_lightcoral": "Koral Muda",
    "color_picker_color_lightcyan": "Sian Muda",
    "color_picker_color_lightgoldenrodyellow": "Kuning Emas Muda",
    "color_picker_color_lightgray": "Abu-abu Muda",
    "color_picker_color_lightgreen": "Hijau Muda",
    "color_picker_color_lightpink": "Merah Muda Terang",
    "color_picker_color_lightsalmon": "Salmon Muda",
    "color_picker_color_lightseagreen": "Hijau Laut Muda",
    "color_picker_color_lightskyblue": "Biru Langit Muda",
    "color_picker_color_lightslategray": "Abu-abu Batu Tulis Muda",
    "color_picker_color_lightsteelblue": "Biru Baja Muda",
    "color_picker_color_lightyellow": "Kuning Muda",
    "color_picker_color_limegreen": "Hijau Limau",
    "color_picker_color_linen": "Linen",
    "color_picker_color_magenta": "Magenta",
    "color_picker_color_mediumaquamarine": "Aquamarine Sedang",
    "color_picker_color_mediumblue": "Biru Sedang",
    "color_picker_color_mediumorchid": "Anggrek Sedang",
    "color_picker_color_mediumpurple": "Ungu Sedang",
    "color_picker_color_mediumseagreen": "Hijau Laut Sedang",
    "color_picker_color_mediumslateblue": "Biru Batu Tulis Sedang",
    "color_picker_color_mediumspringgreen": "Hijau Musim Semi Sedang",
    "color_picker_color_mediumturquoise": "Toska Sedang",
    "color_picker_color_mediumvioletred": "Merah Violet Sedang",
    "color_picker_color_midnightblue": "Biru Tengah Malam",
    "color_picker_color_mintcream": "Krim Mint",
    "color_picker_color_mistyrose": "Mawar Berkabut",
    "color_picker_color_moccasin": "Mokasin",
    "color_picker_color_navajowhite": "Putih Navajo",
    "color_picker_color_oldlace": "Renda Lama",
    "color_picker_color_olivedrab": "Zaitun Kusam",
    "color_picker_color_orange": "Oranye",
    "color_picker_color_orangered": "Merah Oranye",
    "color_picker_color_orchid": "Anggrek",
    "color_picker_color_palegoldenrod": "Batang Emas Pucat",
    "color_picker_color_palegreen": "Hijau Pucat",
    "color_picker_color_paleturquoise": "Toska Pucat",
    "color_picker_color_palevioletred": "Merah Violet Pucat",
    "color_picker_color_papayawhip": "Cambuk Pepaya",
    "color_picker_color_peachpuff": "Persik Puff",
    "color_picker_color_peru": "Peru",
    "color_picker_color_pink": "Merah Muda",
    "color_picker_color_plum": "Plum",
    "color_picker_color_powderblue": "Biru Bedak",
    "color_picker_color_rebeccapurple": "Ungu Rebecca",
    "color_picker_color_rosybrown": "Cokelat Kemerahan",
    "color_picker_color_royalblue": "Biru Royal",
    "color_picker_color_saddlebrown": "Cokelat Pelana",
    "color_picker_color_salmon": "Salmon",
    "color_picker_color_sandybrown": "Cokelat Pasir",
    "color_picker_color_seagreen": "Hijau Laut",
    "color_picker_color_seashell": "Kulit Kerang",
    "color_picker_color_sienna": "Sienna",
    "color_picker_color_skyblue": "Biru Langit",
    "color_picker_color_slateblue": "Biru Batu Tulis",
    "color_picker_color_slategray": "Abu-abu Batu Tulis",
    "color_picker_color_snow": "Salju",
    "color_picker_color_springgreen": "Hijau Musim Semi",
    "color_picker_color_steelblue": "Biru Baja",
    "color_picker_color_tan": "Tan",
    "color_picker_color_thistle": "Thistle",
    "color_picker_color_tomato": "Tomat",
    "color_picker_color_turquoise": "Toska",
    "color_picker_color_violet": "Violet",
    "color_picker_color_wheat": "Gandum",
    "color_picker_color_whitesmoke": "Asap Putih",
    "color_picker_color_yellowgreen": "Kuning Hijau",
}
