# Indonesian lexemes main_menu.py
lexemes = {
    "group_file_label": "Berkas",
    "group_edit_label": "Edit",
    "group_tools_label": "Alat",
    "group_help_label": "Bantuan",

    "actions_file_label_new_document": "Dokumen baru",
    "actions_file_accessible_name_new_document": "Dokumen baru",
    "actions_file_label_open": "Buka",
    "actions_file_accessible_name_open": "Buka dokumen",
    "actions_file_label_save": "Simpan",
    "actions_file_accessible_name_save": "Simpan dokumen",
    "actions_file_label_save_as": "Simpan sebagai",
    "actions_file_accessible_name_save_as": "Simpan salinan dokumen",
    "actions_file_label_settings": "Pengaturan",
    "actions_file_accessible_name_settings": "Pengaturan aplikasi",
    "actions_file_label_reset_settings": "Atur ulang pengaturan",
    "actions_file_accessible_name_reset_settings": "Atur ulang pengaturan",
    "actions_file_label_exit": "Keluar",
    "actions_file_accessible_name_exit": "Keluar dari aplikasi",

    "actions_edit_edit_mode": "Edit",
    "actions_edit_accessible_name_edit_mode": "Edit Berkas",
    "actions_edit_source_mode": "Sumber",
    "actions_edit_accessible_name_source_mode": "Kode Sumber",
    "actions_edit_bold": "Tebal",
    "actions_edit_accessible_name_bold": "Format Teks Tebal",
    "actions_edit_italic": "Miring",
    "actions_edit_accessible_name_italic": "Format Teks Miring",
    "actions_edit_underline": "Garis Bawah",
    "actions_edit_accessible_name_underline": "Format Teks Garis Bawah",
    "actions_edit_strikethrough": "Coret",
    "actions_edit_accessible_name_strikethrough": "Format Teks Coret",
    "actions_edit_blockquote": "Kutipan",
    "actions_edit_accessible_name_blockquote": "Format Teks Kutipan",

    "actions_tools_ai_assistant": "Asisten AI",
    "actions_tools_accessible_name_ai_assistant": "Luncurkan Asisten AI",
    "actions_tools_color_picker": "Pemilih Warna",
    "actions_tools_accessible_name_color_picker": "Pilih Warna Teks",

    "actions_help_label_md_syntax": "Sintaks Markdown",
    "actions_help_accessible_name_md_syntax": "Sintaks Markdown",
    "actions_help_label_check_for_updates": "Periksa Pembaruan",
    "actions_help_accessible_name_check_for_updates": "Periksa Pembaruan",
    "actions_help_label_bug_report":  "Laporan Bug",
    "actions_help_accessible_name_bug_report": "Kirim Laporan Bug",
    "actions_help_label_about": "Tentang",
    "actions_help_accessible_name_about": "Tentang",
}
