# Indonesian lexemes toolbar.py
lexemes = {
    "actions_label_new_document": "Dokumen baru",
    "actions_accessible_name_new_document": "Dokumen baru",
    "actions_label_open": "Buka",
    "actions_accessible_name_open": "Buka dokumen",
    "actions_label_save": "Simpan",
    "actions_accessible_name_save": "Simpan dokumen",
    "actions_label_save_as": "Simpan sebagai",
    "actions_accessible_name_save_as": "Simpan salinan dokumen",
    "actions_label_sync": "Sinkronkan",
    "actions_accessible_name_sync": "Sinkronkan dokumen dengan penyimpanan eksternal",
    "actions_label_edit": "Edit",
    "actions_accessible_name_edit": "Edit berkas",
    "actions_label_source": "Sumber",
    "actions_accessible_name_source": "Kode sumber",
    "actions_label_encrypt": "Enkripsi",
    "actions_accessible_name_encrypt": "Enkripsi berkas",
    "actions_label_decrypt": "Dekripsi",
    "actions_accessible_name_decrypt": "Dekripsi berkas",
    "actions_label_bold": "Tebal",
    "actions_accessible_name_bold": "Format teks tebal",
    "actions_label_italic": "Miring",
    "actions_accessible_name_italic": "Format teks miring",
    "actions_label_underline": "Garis bawah",
    "actions_accessible_name_underline": "Format teks garis bawah",
    "actions_label_strikethrough": "Coret",
    "actions_accessible_name_strikethrough": "Format teks coret",
    "actions_label_blockquote": "Kutipan",
    "actions_accessible_name_blockquote": "Format teks kutipan",
    "actions_label_color_picker": "Pemilih Warna",
    "actions_accessible_name_color_picker": "Pilih warna teks",
    "actions_label_ai_assistant": "Asisten AI",
    "actions_accessible_name_ai_assistant": "Luncurkan Asisten AI",
    "actions_label_about": "Tentang",
    "actions_accessible_name_about": "Tentang Aplikasi",
    "actions_label_exit": "Keluar",
    "actions_accessible_name_exit": "Keluar dari Aplikasi",
    "actions_label_settings": "Pengaturan",
    "actions_accessible_name_settings": "Pengaturan aplikasi",

    "search_input_label": "Cari",
    "search_input_placeholder_text": "Cari teks dalam dokumen",
    "search_input_accessible_description": "Kolom input pencarian",
    "search_buttons_label_clear": "Hapus pencarian",
    "search_buttons_accessible_name_clear": "Hapus kolom input pencarian",
    "search_buttons_label_prev": "Pencarian sebelumnya",
    "search_buttons_accessible_name_prev": "Hasil pencarian sebelumnya",
    "search_buttons_label_next": "Pencarian berikutnya",
    "search_buttons_accessible_name_next": "Hasil pencarian berikutnya",
    "search_case_sensitive_accessible_name": "Peka huruf besar-kecil",
    "search_case_sensitive_tooltip": "Pencarian peka huruf besar-kecil",
}
