# Finnish lexemes main_menu.py
lexemes = {
    "group_file_label": "Tiedosto",
    "group_edit_label": "Muokkaa",
    "group_tools_label": "Työkalut",
    "group_help_label": "Apua",

    "actions_file_label_new_document": "Uusi asiakirja",
    "actions_file_accessible_name_new_document": "Uusi asiakirja",
    "actions_file_label_open": "Avaa",
    "actions_file_accessible_name_open": "Avaa asiakirja",
    "actions_file_label_save": "Tallenna",
    "actions_file_accessible_name_save": "Tallenna asiakirja",
    "actions_file_label_save_as": "Tallenna nimellä",
    "actions_file_accessible_name_save_as": "Tallenna asiakirjan kopio",
    "actions_file_label_exit": "Poistu",
    "actions_file_accessible_name_exit": "Poistu sovelluksesta",

    "edit_actions_edit_mode": "Muokkaa",
    "edit_actions_accessible_name_edit_mode": "Muokkaa tiedostoa",
    "edit_actions_source_mode": "Lähdekoodi",
    "edit_actions_accessible_name_source_mode": "Lähdekoodi",
    "edit_actions_bold": "Lihavoitu",
    "edit_actions_accessible_name_bold": "Lihavoi teksti",
    "edit_actions_italic": "Kursivoitu",
    "edit_actions_accessible_name_italic": "Kursivoi teksti",
    "edit_actions_underline": "Alleviivaus",
    "edit_actions_accessible_name_underline": "Alleviivaa teksti",
    "edit_actions_strikethrough": "Yliviivaus",
    "edit_actions_accessible_name_strikethrough": "Yliviivaa teksti",
    "edit_actions_blockquote": "Lainaus",
    "edit_actions_accessible_name_blockquote": "Lainaa teksti",

    "tools_actions_ai_assistant": "Tekoälyavustaja",
    "tools_actions_accessible_name_ai_assistant": "Käynnistä tekoälyavustaja",
    "tools_actions_color_picker": "Värinvalitsin",
    "tools_actions_accessible_name_color_picker": "Valitse tekstiväri",

    "actions_help_label_md_syntax": "Markdown-syntaksi",
    "actions_help_accessible_name_md_syntax": "Markdown-syntaksi",
    "actions_help_label_check_for_updates": "Tarkista päivitykset",
    "actions_help_accessible_name_check_for_updates": "Tarkista päivitykset",
    "actions_help_label_bug_report":  "Vikailmoitus",
    "actions_help_accessible_name_bug_report": "Lähetä vikailmoitus",
    "actions_help_label_about": "Tietoja",
    "actions_help_accessible_name_about": "Tietoja",
}
