# Russian lexemes main_menu.py
lexemes = {
    "group_file_label": "Файл",
    "group_edit_label": "Редактировать",
    "group_tools_label": "Инструменты",
    "group_help_label": "Помощь",

    "actions_file_label_new_document": "Новый документ",
    "actions_file_accessible_name_new_document": "Новый документ",
    "actions_file_label_open": "Открыть",
    "actions_file_accessible_name_open": "Открыть документ",
    "actions_file_label_save": "Сохранить",
    "actions_file_accessible_name_save": "Сохранить документ",
    "actions_file_label_save_as": "Сохранить как",
    "actions_file_accessible_name_save_as": "Сохранить копию документа",
    "actions_file_label_exit": "Выйти из приложения",
    "actions_file_accessible_name_exit": "Выйти из приложения",

    "edit_actions_edit_mode": "Редактировать",
    "edit_actions_accessible_name_edit_mode": "Редактировать файл",
    "edit_actions_source_mode": "Исходник",
    "edit_actions_accessible_name_source_mode": "Исходный код",
    "edit_actions_bold": "Жирный",
    "edit_actions_accessible_name_bold": "Формат жирного текста",
    "edit_actions_italic": "Курсив",
    "edit_actions_accessible_name_italic": "Формат курсивного текста",
    "edit_actions_underline": "Подчеркнутый",
    "edit_actions_accessible_name_underline": "Формат подчеркнутого текста",
    "edit_actions_strikethrough": "Зачеркнутый",
    "edit_actions_accessible_name_strikethrough": "Формат зачеркнутого текста",
    "edit_actions_blockquote": "Блок цитаты",
    "edit_actions_accessible_name_blockquote": "Формат текста цитаты",

    "tools_actions_ai_assistant": "ИИ Ассистент",
    "tools_actions_accessible_name_ai_assistant": "Запустить ИИ Ассистент",
    "tools_actions_color_picker": "Выбор цвета",
    "tools_actions_accessible_name_color_picker": "Выбрать цвет текста",

    "actions_help_label_md_syntax": "Синтаксис Markdown",
    "actions_help_accessible_name_md_syntax": "Синтаксис Markdown",
    "actions_help_label_check_for_updates": "Проверить обновления",
    "actions_help_accessible_name_check_for_updates": "Проверить обновления",
    "actions_help_label_bug_report": "Сообщить об ошибке",
    "actions_help_accessible_name_bug_report": "Отправить отчет об ошибке",
    "actions_help_label_about": "О программе",
    "actions_help_accessible_name_about": "О программе",
}
