# English lexemes main_menu.py
lexemes = {
    "group_file_label": "File",
    "group_edit_label": "Edit",
    "group_tools_label": "Tools",
    "group_help_label": "Help",

    "actions_file_label_new_document": "New document",
    "actions_file_accessible_name_new_document": "New document",
    "actions_file_label_open": "Open",
    "actions_file_accessible_name_open": "Open document",
    "actions_file_label_save": "Save",
    "actions_file_accessible_name_save": "Save document",
    "actions_file_label_save_as": "Save as",
    "actions_file_accessible_name_save_as": "Save as document copy",
    "actions_file_label_exit": "Exit",
    "actions_file_accessible_name_exit": "Exit the app",

    "edit_actions_edit_mode": "Edit",
    "edit_actions_accessible_name_edit_mode": "Edit File",
    "edit_actions_source_mode": "Source",
    "edit_actions_accessible_name_source_mode": "Source Code",
    "edit_actions_bold": "Bold",
    "edit_actions_accessible_name_bold": "Bold Text Format",
    "edit_actions_italic": "Italic",
    "edit_actions_accessible_name_italic": "Italic Text Format",
    "edit_actions_underline": "Underline",
    "edit_actions_accessible_name_underline": "Underline Text Format",
    "edit_actions_strikethrough": "Strikethrough",
    "edit_actions_accessible_name_strikethrough": "Strikethrough Text Format",
    "edit_actions_blockquote": "Blockquote",
    "edit_actions_accessible_name_blockquote": "Blockquote Text Format",

    "tools_actions_ai_assistant": "AI Assistant",
    "tools_actions_accessible_name_ai_assistant": "Launch AI Assistant",
    "tools_actions_color_picker": "Color Picker",
    "tools_actions_accessible_name_color_picker": "Choose a Text Color",

    "actions_help_label_md_syntax": "Markdown Syntax",
    "actions_help_accessible_name_md_syntax": "Markdown Syntax",
    "actions_help_label_check_for_updates": "Check for Updates",
    "actions_help_accessible_name_check_for_updates": "Check for Updates",
    "actions_help_label_bug_report":  "Bug Report",
    "actions_help_accessible_name_bug_report": "Submit Bug Report",
    "actions_help_label_about": "About",
    "actions_help_accessible_name_about": "About",
}
