# Spanish lexemes main_menu.py
lexemes = {
    "group_file_label": "Archivo",
    "group_edit_label": "Editar",
    "group_tools_label": "Herramientas",
    "group_help_label": "Ayuda",

    "actions_file_label_new_document": "Nuevo documento",
    "actions_file_accessible_name_new_document": "Nuevo documento",
    "actions_file_label_open": "Abrir",
    "actions_file_accessible_name_open": "Abrir documento",
    "actions_file_label_save": "Guardar",
    "actions_file_accessible_name_save": "Guardar documento",
    "actions_file_label_save_as": "Guardar como",
    "actions_file_accessible_name_save_as": "Guardar como copia del documento",
    "actions_file_label_exit": "Salir",
    "actions_file_accessible_name_exit": "Salir de la aplicación",

    "edit_actions_edit_mode": "Editar",
    "edit_actions_accessible_name_edit_mode": "Editar archivo",
    "edit_actions_source_mode": "Fuente",
    "edit_actions_accessible_name_source_mode": "Código fuente",
    "edit_actions_bold": "Negrita",
    "edit_actions_accessible_name_bold": "Formato de texto en negrita",
    "edit_actions_italic": "Cursiva",
    "edit_actions_accessible_name_italic": "Formato de texto en cursiva",
    "edit_actions_underline": "Subrayado",
    "edit_actions_accessible_name_underline": "Formato de texto subrayado",
    "edit_actions_strikethrough": "Tachado",
    "edit_actions_accessible_name_strikethrough": "Formato de texto tachado",
    "edit_actions_blockquote": "Cita",
    "edit_actions_accessible_name_blockquote": "Formato de texto de cita",

    "tools_actions_ai_assistant": "Asistente de IA",
    "tools_actions_accessible_name_ai_assistant": "Lanzar el asistente de IA",
    "tools_actions_color_picker": "Selector de color",
    "tools_actions_accessible_name_color_picker": "Elegir un color de texto",

    "actions_help_label_md_syntax": "Sintaxis Markdown",
    "actions_help_accessible_name_md_syntax": "Sintaxis Markdown",
    "actions_help_label_check_for_updates": "Buscar actualizaciones",
    "actions_help_accessible_name_check_for_updates": "Buscar actualizaciones",
    "actions_help_label_bug_report": "Reportar error",
    "actions_help_accessible_name_bug_report": "Enviar reporte de error",
    "actions_help_label_about": "Acerca de",
    "actions_help_accessible_name_about": "Acerca de",
}
