# German lexemes main_menu.py
lexemes = {
    "group_file_label": "Datei",
    "group_edit_label": "Bearbeiten",
    "group_tools_label": "Werkzeuge",
    "group_help_label": "Hilfe",

    "actions_file_label_new_document": "Neues Dokument",
    "actions_file_accessible_name_new_document": "Neues Dokument",
    "actions_file_label_open": "Öffnen",
    "actions_file_accessible_name_open": "Dokument öffnen",
    "actions_file_label_save": "Speichern",
    "actions_file_accessible_name_save": "Dokument speichern",
    "actions_file_label_save_as": "Speichern unter",
    "actions_file_accessible_name_save_as": "Kopie des Dokuments speichern",
    "actions_file_label_exit": "Beenden",
    "actions_file_accessible_name_exit": "App beenden",

    "edit_actions_edit_mode": "Bearbeiten",
    "edit_actions_accessible_name_edit_mode": "Datei bearbeiten",
    "edit_actions_source_mode": "Quelle",
    "edit_actions_accessible_name_source_mode": "Quellcode",
    "edit_actions_bold": "Fett",
    "edit_actions_accessible_name_bold": "Fettschrift Format",
    "edit_actions_italic": "Kursiv",
    "edit_actions_accessible_name_italic": "Kursivschrift Format",
    "edit_actions_underline": "Unterstreichen",
    "edit_actions_accessible_name_underline": "Unterstrichen Textformat",
    "edit_actions_strikethrough": "Durchgestrichen",
    "edit_actions_accessible_name_strikethrough": "Durchgestrichenes Textformat",
    "edit_actions_blockquote": "Blockzitat",
    "edit_actions_accessible_name_blockquote": "Blockzitat Textformat",

    "tools_actions_ai_assistant": "KI-Assistent",
    "tools_actions_accessible_name_ai_assistant": "KI-Assistent starten",
    "tools_actions_color_picker": "Farbwähler",
    "tools_actions_accessible_name_color_picker": "Textfarbe auswählen",

    "actions_help_label_md_syntax": "Markdown-Syntax",
    "actions_help_accessible_name_md_syntax": "Markdown-Syntax",
    "actions_help_label_check_for_updates": "Auf Updates prüfen",
    "actions_help_accessible_name_check_for_updates": "Auf Updates prüfen",
    "actions_help_label_bug_report": "Fehlerbericht",
    "actions_help_accessible_name_bug_report": "Fehlerbericht senden",
    "actions_help_label_about": "Über",
    "actions_help_accessible_name_about": "Über",
}
