# Chinese lexemes common.py
lexemes = {
    "module_text_to_speech_name": "文本朗读",
    "module_text_to_speech_action_read_selection": "朗读所选文本",
    "module_text_to_speech_action_read_file": "朗读文件",
    "module_text_to_speech_action_read": "朗读",
    "module_text_to_speech_action_read_document": "朗读文档",
    "module_text_to_speech_action_pause_resume": "暂停／继续",
    "module_text_to_speech_action_stop": "停止朗读",
    "module_text_to_speech_playback_details": "播放详情",
    "module_text_to_speech_model_not_loaded": "未加载",
    "module_text_to_speech_playback_model": "模型：{value}",
    "module_text_to_speech_playback_codec": "编解码器模型：{value}",
    "module_text_to_speech_playback_voice": "声音：{value}",
    "module_text_to_speech_playback_language": "语言：{value}",
    "module_text_to_speech_playback_sample_rate": "采样率：{value}",
    "module_text_to_speech_playback_rate": "播放采样率：{value}",
    "module_text_to_speech_playback_audio_format": "音频格式：PCM，16 位有符号，单声道",
    "module_text_to_speech_playback_speed": "速度：{value}",
    "module_text_to_speech_playback_runtime": "运行程序：{value}",
    "module_text_to_speech_dependency_required": "需要 {value}",
    "module_text_to_speech_status_ready": "可以开始朗读",
    "module_text_to_speech_status_stopped": "已停止。",
    "module_text_to_speech_status_finished": "朗读完毕。",
    "module_text_to_speech_status_unavailable": "语音不可用。",
    "module_text_to_speech_status_empty": "没有可朗读的内容。",
    "module_text_to_speech_status_loading": "正在加载语音模型…",
    "module_text_to_speech_status_preparing": "正在准备语音…",
    "module_text_to_speech_status_reading": "正在朗读…",
    "module_text_to_speech_status_paused": "已暂停。",
    "module_text_to_speech_error": "错误：{error}",
    "module_text_to_speech_language_en": "英语",
    "module_text_to_speech_language_es": "西班牙语",
    "module_text_to_speech_language_de": "德语",
    "module_text_to_speech_language_fr": "法语",
    "module_text_to_speech_language_it": "意大利语",
    "module_text_to_speech_language_vi": "越南语",
    "module_text_to_speech_language_hi": "印地语",
    "module_text_to_speech_language_zh": "中文（普通话）",
    "module_text_to_speech_language_ja": "日语",
    "module_text_to_speech_language_runtime_required": "需要运行程序支持",
    "module_text_to_speech_error_note_locked": "请先打开并解锁此笔记，然后再朗读。",
    "module_text_to_speech_error_read_note": "无法读取此笔记：{error}",
    "module_text_to_speech_action_read_from_cursor": "从光标处开始朗读",
}
