# Italian lexemes common.py
lexemes = {
    "module_text_to_speech_name": "Sintesi vocale",
    "module_text_to_speech_action_read_selection": "Leggi selezione ad alta voce",
    "module_text_to_speech_action_read_file": "Leggi file ad alta voce",
    "module_text_to_speech_action_read": "Leggi ad alta voce",
    "module_text_to_speech_action_read_document": "Leggi documento ad alta voce",
    "module_text_to_speech_action_pause_resume": "Pausa / Riprendi",
    "module_text_to_speech_action_stop": "Interrompi lettura",
    "module_text_to_speech_playback_details": "Dettagli riproduzione",
    "module_text_to_speech_model_not_loaded": "Non caricato",
    "module_text_to_speech_playback_model": "Modello: {value}",
    "module_text_to_speech_playback_codec": "Modello codec: {value}",
    "module_text_to_speech_playback_voice": "Voce: {value}",
    "module_text_to_speech_playback_language": "Lingua: {value}",
    "module_text_to_speech_playback_sample_rate": "Frequenza di campionamento: {value}",
    "module_text_to_speech_playback_rate": "Frequenza di riproduzione: {value}",
    "module_text_to_speech_playback_audio_format": "Formato audio: PCM, 16 bit con segno, mono",
    "module_text_to_speech_playback_speed": "Velocità: {value}",
    "module_text_to_speech_playback_runtime": "Motore: {value}",
    "module_text_to_speech_dependency_required": "Richiesto {value}",
    "module_text_to_speech_status_ready": "Pronto per leggere",
    "module_text_to_speech_status_stopped": "Interrotto.",
    "module_text_to_speech_status_finished": "Lettura terminata.",
    "module_text_to_speech_status_unavailable": "Sintesi vocale non disponibile.",
    "module_text_to_speech_status_empty": "Nulla da leggere.",
    "module_text_to_speech_status_loading": "Caricamento modello vocale…",
    "module_text_to_speech_status_preparing": "Preparazione voce…",
    "module_text_to_speech_status_reading": "Lettura ad alta voce…",
    "module_text_to_speech_status_paused": "In pausa.",
    "module_text_to_speech_error": "Errore: {error}",
    "module_text_to_speech_language_en": "Inglese",
    "module_text_to_speech_language_es": "Spagnolo",
    "module_text_to_speech_language_de": "Tedesco",
    "module_text_to_speech_language_fr": "Francese",
    "module_text_to_speech_language_it": "Italiano",
    "module_text_to_speech_language_vi": "Vietnamita",
    "module_text_to_speech_language_hi": "Hindi",
    "module_text_to_speech_language_zh": "Cinese (mandarino)",
    "module_text_to_speech_language_ja": "Giapponese",
    "module_text_to_speech_language_runtime_required": "richiede un motore compatibile",
    "module_text_to_speech_error_note_locked": "Apri e sblocca la nota prima di leggerla ad alta voce.",
    "module_text_to_speech_error_read_note": "Impossibile leggere la nota: {error}",
    "module_text_to_speech_action_read_from_cursor": "Leggi ad alta voce dal cursore",
}
