# Turkish lexemes main_menu.py
lexemes = {
    "group_file_label": "Dosya",
    "group_edit_label": "Düzenle",
    "group_tools_label": "Araçlar",
    "group_help_label": "Yardım",

    "actions_file_label_new_document": "Yeni belge",
    "actions_file_accessible_name_new_document": "Yeni belge",
    "actions_file_label_open": "Aç",
    "actions_file_accessible_name_open": "Belgeyi aç",
    "actions_file_label_save": "Kaydet",
    "actions_file_accessible_name_save": "Belgeyi kaydet",
    "actions_file_label_save_as": "Farklı Kaydet",
    "actions_file_accessible_name_save_as": "Belgeyi kopya olarak kaydet",
    "actions_file_label_exit": "Çıkış",
    "actions_file_accessible_name_exit": "Uygulamadan çık",

    "edit_actions_edit_mode": "Düzenle",
    "edit_actions_accessible_name_edit_mode": "Dosyayı düzenle",
    "edit_actions_source_mode": "Kaynak",
    "edit_actions_accessible_name_source_mode": "Kaynak kodu",
    "edit_actions_bold": "Kalın",
    "edit_actions_accessible_name_bold": "Kalın metin biçimi",
    "edit_actions_italic": "İtalik",
    "edit_actions_accessible_name_italic": "İtalik metin biçimi",
    "edit_actions_underline": "Altı çizili",
    "edit_actions_accessible_name_underline": "Altı çizili metin biçimi",
    "edit_actions_strikethrough": "Üstü çizili",
    "edit_actions_accessible_name_strikethrough": "Üstü çizili metin biçimi",
    "edit_actions_blockquote": "Alıntı",
    "edit_actions_accessible_name_blockquote": "Alıntı metin biçimi",

    "tools_actions_ai_assistant": "AI Asistanı",
    "tools_actions_accessible_name_ai_assistant": "AI Asistanını Başlat",
    "tools_actions_color_picker": "Renk Seçici",
    "tools_actions_accessible_name_color_picker": "Metin rengi seç",

    "actions_help_label_md_syntax": "Markdown Sözdizimi",
    "actions_help_accessible_name_md_syntax": "Markdown Sözdizimi",
    "actions_help_label_check_for_updates": "Güncellemeleri Denetle",
    "actions_help_accessible_name_check_for_updates": "Güncellemeleri denetle",
    "actions_help_label_bug_report": "Hata Raporu",
    "actions_help_accessible_name_bug_report": "Hata raporu gönder",
    "actions_help_label_about": "Hakkında",
    "actions_help_accessible_name_about": "Hakkında",
}
