# Dutch lexemes main_menu.py
lexemes = {
    "group_file_label": "Bestand",
    "group_edit_label": "Bewerken",
    "group_tools_label": "Gereedschappen",
    "group_help_label": "Hulp",

    "actions_file_label_new_document": "Nieuw document",
    "actions_file_accessible_name_new_document": "Nieuw document",
    "actions_file_label_open": "Openen",
    "actions_file_accessible_name_open": "Document openen",
    "actions_file_label_save": "Opslaan",
    "actions_file_accessible_name_save": "Document opslaan",
    "actions_file_label_save_as": "Opslaan als",
    "actions_file_accessible_name_save_as": "Opslaan als documentkopie",
    "actions_file_label_exit": "Afsluiten",
    "actions_file_accessible_name_exit": "De app verlaten",

    "edit_actions_edit_mode": "Bewerken",
    "edit_actions_accessible_name_edit_mode": "Bestand bewerken",
    "edit_actions_source_mode": "Bron",
    "edit_actions_accessible_name_source_mode": "Broncode",
    "edit_actions_bold": "Vet",
    "edit_actions_accessible_name_bold": "Tekst in vetformaat",
    "edit_actions_italic": "Cursief",
    "edit_actions_accessible_name_italic": "Tekst in cursief formaat",
    "edit_actions_underline": "Onderstrepen",
    "edit_actions_accessible_name_underline": "Tekst onderstrepen",
    "edit_actions_strikethrough": "Doorhalen",
    "edit_actions_accessible_name_strikethrough": "Tekst doorhalen",
    "edit_actions_blockquote": "Citaat",
    "edit_actions_accessible_name_blockquote": "Tekst in citaatformaat",

    "tools_actions_ai_assistant": "AI Assistent",
    "tools_actions_accessible_name_ai_assistant": "AI Assistent starten",
    "tools_actions_color_picker": "Kleurkiezer",
    "tools_actions_accessible_name_color_picker": "Kies een tekstkleur",

    "actions_help_label_md_syntax": "Markdown-syntax",
    "actions_help_accessible_name_md_syntax": "Markdown-syntax",
    "actions_help_label_check_for_updates": "Controleer op updates",
    "actions_help_accessible_name_check_for_updates": "Controleer op updates",
    "actions_help_label_bug_report": "Bugrapport",
    "actions_help_accessible_name_bug_report": "Bugrapport indienen",
    "actions_help_label_about": "Over",
    "actions_help_accessible_name_about": "Over",
}
