# Italian lexemes main_menu.py
lexemes = {
    "group_file_label": "File",
    "group_edit_label": "Modifica",
    "group_tools_label": "Strumenti",
    "group_help_label": "Aiuto",

    "actions_file_label_new_document": "Nuovo documento",
    "actions_file_accessible_name_new_document": "Nuovo documento",
    "actions_file_label_open": "Apri",
    "actions_file_accessible_name_open": "Apri documento",
    "actions_file_label_save": "Salva",
    "actions_file_accessible_name_save": "Salva documento",
    "actions_file_label_save_as": "Salva come",
    "actions_file_accessible_name_save_as": "Salva come copia del documento",
    "actions_file_label_exit": "Esci",
    "actions_file_accessible_name_exit": "Esci dall'applicazione",

    "edit_actions_edit_mode": "Modifica",
    "edit_actions_accessible_name_edit_mode": "Modifica file",
    "edit_actions_source_mode": "Sorgente",
    "edit_actions_accessible_name_source_mode": "Codice sorgente",
    "edit_actions_bold": "Grassetto",
    "edit_actions_accessible_name_bold": "Formato testo grassetto",
    "edit_actions_italic": "Corsivo",
    "edit_actions_accessible_name_italic": "Formato testo corsivo",
    "edit_actions_underline": "Sottolineato",
    "edit_actions_accessible_name_underline": "Formato testo sottolineato",
    "edit_actions_strikethrough": "Barrato",
    "edit_actions_accessible_name_strikethrough": "Formato testo barrato",
    "edit_actions_blockquote": "Citazione",
    "edit_actions_accessible_name_blockquote": "Formato testo citazione",

    "tools_actions_ai_assistant": "Assistente IA",
    "tools_actions_accessible_name_ai_assistant": "Avvia Assistente IA",
    "tools_actions_color_picker": "Selettore Colore",
    "tools_actions_accessible_name_color_picker": "Scegli un colore per il testo",

    "actions_help_label_md_syntax": "Sintassi Markdown",
    "actions_help_accessible_name_md_syntax": "Sintassi Markdown",
    "actions_help_label_check_for_updates": "Controlla aggiornamenti",
    "actions_help_accessible_name_check_for_updates": "Controlla aggiornamenti",
    "actions_help_label_bug_report": "Segnala bug",
    "actions_help_accessible_name_bug_report": "Invia segnalazione di bug",
    "actions_help_label_about": "Informazioni",
    "actions_help_accessible_name_about": "Informazioni",
}
