# Korean lexemes common.py
lexemes = {
    "module_text_to_speech_name": "텍스트 음성 변환",
    "module_text_to_speech_action_read_selection": "선택한 텍스트 읽기",
    "module_text_to_speech_action_read_file": "파일 읽기",
    "module_text_to_speech_action_read": "소리 내어 읽기",
    "module_text_to_speech_action_read_document": "문서 읽기",
    "module_text_to_speech_action_pause_resume": "일시 정지 / 재개",
    "module_text_to_speech_action_stop": "읽기 중지",
    "module_text_to_speech_playback_details": "재생 정보",
    "module_text_to_speech_model_not_loaded": "로드되지 않음",
    "module_text_to_speech_playback_model": "모델: {value}",
    "module_text_to_speech_playback_codec": "코덱 모델: {value}",
    "module_text_to_speech_playback_voice": "음성: {value}",
    "module_text_to_speech_playback_language": "언어: {value}",
    "module_text_to_speech_playback_sample_rate": "샘플 레이트: {value}",
    "module_text_to_speech_playback_rate": "재생 레이트: {value}",
    "module_text_to_speech_playback_audio_format": "오디오 형식: PCM, 부호 있는 16비트, 모노",
    "module_text_to_speech_playback_speed": "속도: {value}",
    "module_text_to_speech_playback_runtime": "런타임: {value}",
    "module_text_to_speech_dependency_required": "{value} 필요",
    "module_text_to_speech_status_ready": "읽기 준비 완료",
    "module_text_to_speech_status_stopped": "중지됨.",
    "module_text_to_speech_status_finished": "읽기 완료.",
    "module_text_to_speech_status_unavailable": "음성을 사용할 수 없습니다.",
    "module_text_to_speech_status_empty": "읽을 내용이 없습니다.",
    "module_text_to_speech_status_loading": "음성 모델 로드 중…",
    "module_text_to_speech_status_preparing": "음성 준비 중…",
    "module_text_to_speech_status_reading": "읽는 중…",
    "module_text_to_speech_status_paused": "일시 정지됨.",
    "module_text_to_speech_error": "오류: {error}",
    "module_text_to_speech_language_en": "영어",
    "module_text_to_speech_language_es": "스페인어",
    "module_text_to_speech_language_de": "독일어",
    "module_text_to_speech_language_fr": "프랑스어",
    "module_text_to_speech_language_it": "이탈리아어",
    "module_text_to_speech_language_vi": "베트남어",
    "module_text_to_speech_language_hi": "힌디어",
    "module_text_to_speech_language_zh": "중국어(표준어)",
    "module_text_to_speech_language_ja": "일본어",
    "module_text_to_speech_language_runtime_required": "런타임 지원 필요",
    "module_text_to_speech_error_note_locked": "읽기 전에 이 노트를 열고 잠금을 해제하세요.",
    "module_text_to_speech_error_read_note": "이 노트를 읽을 수 없습니다: {error}",
    "module_text_to_speech_action_read_from_cursor": "커서 위치부터 읽기",
}
