viewer_color_s=grey
viewer_color_todo=red
viewer_background_color_todo=lightGrey

# Admonition title colors
adm_note_color=0xffffff
adm_info_color=0xffffff
adm_tip_color=0xffffff
adm_hint_color=0xffffff
adm_warning_color=0xff0000
adm_caution_color=0xff0000
adm_danger_color=0xff0000
adm_error_color=0xffffff
adm_success_color=0xffffff
adm_question_color=0xffffff
adm_abstract_color=0xffffff
adm_summary_color=0xffffff
adm_example_color=0xffffff
adm_bug_color=0xffffff
adm_quote_color=0xffffff
adm_failure_color=0xffffff

# Admonition title backgrounds
adm_note_bg=black
adm_info_bg=black
adm_tip_bg=black
adm_hint_bg=black
adm_warning_bg=black
adm_caution_bg=black
adm_danger_bg=black
adm_error_bg=black
adm_success_bg=black
adm_question_bg=black
adm_abstract_bg=black
adm_summary_bg=black
adm_example_bg=black
adm_bug_bg=black
adm_quote_bg=black
adm_failure_bg=black
