viewer_color_s=grey
viewer_color_todo=white
viewer_background_color_todo=red

# Admonition title colors
adm_note_color=0xffffff
adm_info_color=0xffffff
adm_tip_color=0xffffff
adm_hint_color=0xffffff
adm_warning_color=0xffffff
adm_caution_color=0xffffff
adm_danger_color=0xffffff
adm_error_color=0xffffff
adm_success_color=0xffffff
adm_question_color=0xffffff
adm_abstract_color=0xffffff
adm_summary_color=0xffffff
adm_example_color=0xffffff
adm_bug_color=0xffffff
adm_quote_color=0xffffff
adm_failure_color=0xffffff

# Admonition title backgrounds
adm_note_bg=dimGrey
adm_info_bg=dimGrey
adm_tip_bg=dimGrey
adm_hint_bg=dimGrey
adm_warning_bg=red
adm_caution_bg=red
adm_danger_bg=red
adm_error_bg=dimGrey
adm_success_bg=dimGrey
adm_question_bg=dimGrey
adm_abstract_bg=dimGrey
adm_summary_bg=dimGrey
adm_example_bg=dimGrey
adm_bug_bg=dimGrey
adm_quote_bg=dimGrey
adm_failure_bg=dimGrey
