# Georgian lexemes main_menu.py
lexemes = {
    "group_file_label": "ფაილი",
    "group_edit_label": "რედაქტირება",
    "group_tools_label": "ინსტრუმენტები",
    "group_help_label": "დახმარება",

    "actions_file_label_new_document": "ახალი დოკუმენტი",
    "actions_file_accessible_name_new_document": "ახალი დოკუმენტი",
    "actions_file_label_open": "გახსნა",
    "actions_file_accessible_name_open": "დოკუმენტის გახსნა",
    "actions_file_label_save": "შენახვა",
    "actions_file_accessible_name_save": "დოკუმენტის შენახვა",
    "actions_file_label_save_as": "შენახვა როგორც",
    "actions_file_accessible_name_save_as": "დოკუმენტის ასლის შენახვა",
    "actions_file_label_exit": "გასვლა",
    "actions_file_accessible_name_exit": "აპლიკაციის დატოვება",

    "edit_actions_edit_mode": "რედაქტირების რეჟიმი",
    "edit_actions_accessible_name_edit_mode": "ფაილის რედაქტირება",
    "edit_actions_source_mode": "წყარო",
    "edit_actions_accessible_name_source_mode": "წყაროს კოდი",
    "edit_actions_bold": "მუქი",
    "edit_actions_accessible_name_bold": "ტექსტის მუქი ფორმატი",
    "edit_actions_italic": "კურსივი",
    "edit_actions_accessible_name_italic": "ტექსტის კურსივის ფორმატი",
    "edit_actions_underline": "ხაზგასმა",
    "edit_actions_accessible_name_underline": "ტექსტის ხაზგასმის ფორმატი",
    "edit_actions_strikethrough": "ხაზზეთმის ფორმატი",
    "edit_actions_accessible_name_strikethrough": "ტექსტის ხაზზეთმის ფორმატი",
    "edit_actions_blockquote": "ციტატა",
    "edit_actions_accessible_name_blockquote": "ტექსტის ციტირების ფორმატი",

    "tools_actions_ai_assistant": "AI ასისტენტი",
    "tools_actions_accessible_name_ai_assistant": "AI ასისტენტის გაშვება",
    "tools_actions_color_picker": "ფერის შერჩევის ინსტრუმენტი",
    "tools_actions_accessible_name_color_picker": "ტექსტის ფერის არჩევა",

    "actions_help_label_md_syntax": "Markdown სინტაქსი",
    "actions_help_accessible_name_md_syntax": "Markdown სინტაქსი",
    "actions_help_label_check_for_updates": "განახლებების შემოწმება",
    "actions_help_accessible_name_check_for_updates": "განახლებების შემოწმება",
    "actions_help_label_bug_report": "შეცდომის რეპორტი",
    "actions_help_accessible_name_bug_report": "შეცდომის რეპორტის შეყვანა",
    "actions_help_label_about": "შესახებ",
    "actions_help_accessible_name_about": "აპლიკაციის შესახებ",
}
