# French lexemes main_menu.py
lexemes = {
    "group_file_label": "Fichier",
    "group_edit_label": "Éditer",
    "group_tools_label": "Outils",
    "group_help_label": "Aide",

    "actions_file_label_new_document": "Nouveau document",
    "actions_file_accessible_name_new_document": "Nouveau document",
    "actions_file_label_open": "Ouvrir",
    "actions_file_accessible_name_open": "Ouvrir le document",
    "actions_file_label_save": "Enregistrer",
    "actions_file_accessible_name_save": "Enregistrer le document",
    "actions_file_label_save_as": "Enregistrer sous",
    "actions_file_accessible_name_save_as": "Enregistrer une copie du document",
    "actions_file_label_exit": "Quitter",
    "actions_file_accessible_name_exit": "Quitter l'application",

    "edit_actions_edit_mode": "Modifier",
    "edit_actions_accessible_name_edit_mode": "Modifier le fichier",
    "edit_actions_source_mode": "Source",
    "edit_actions_accessible_name_source_mode": "Code source",
    "edit_actions_bold": "Gras",
    "edit_actions_accessible_name_bold": "Format de texte en gras",
    "edit_actions_italic": "Italique",
    "edit_actions_accessible_name_italic": "Format de texte en italique",
    "edit_actions_underline": "Souligner",
    "edit_actions_accessible_name_underline": "Format de texte souligné",
    "edit_actions_strikethrough": "Barré",
    "edit_actions_accessible_name_strikethrough": "Format de texte barré",
    "edit_actions_blockquote": "Citation",
    "edit_actions_accessible_name_blockquote": "Format de texte de citation",

    "tools_actions_ai_assistant": "Assistant IA",
    "tools_actions_accessible_name_ai_assistant": "Lancer l'assistant IA",
    "tools_actions_color_picker": "Sélecteur de couleur",
    "tools_actions_accessible_name_color_picker": "Choisir une couleur de texte",

    "actions_help_label_md_syntax": "Syntaxe Markdown",
    "actions_help_accessible_name_md_syntax": "Syntaxe Markdown",
    "actions_help_label_check_for_updates": "Vérifier les mises à jour",
    "actions_help_accessible_name_check_for_updates": "Vérifier les mises à jour",
    "actions_help_label_bug_report": "Rapport de bug",
    "actions_help_accessible_name_bug_report": "Soumettre un rapport de bug",
    "actions_help_label_about": "À propos",
    "actions_help_accessible_name_about": "À propos",
}
