# Portuguese lexemes common.py
lexemes = {
    "module_text_to_speech_name": "Texto para fala",
    "module_text_to_speech_action_read_selection": "Ler seleção em voz alta",
    "module_text_to_speech_action_read_file": "Ler arquivo em voz alta",
    "module_text_to_speech_action_read": "Ler em voz alta",
    "module_text_to_speech_action_read_document": "Ler documento em voz alta",
    "module_text_to_speech_action_pause_resume": "Pausar / Retomar",
    "module_text_to_speech_action_stop": "Parar leitura",
    "module_text_to_speech_playback_details": "Detalhes da reprodução",
    "module_text_to_speech_model_not_loaded": "Não carregado",
    "module_text_to_speech_playback_model": "Modelo: {value}",
    "module_text_to_speech_playback_codec": "Modelo de codec: {value}",
    "module_text_to_speech_playback_voice": "Voz: {value}",
    "module_text_to_speech_playback_language": "Idioma: {value}",
    "module_text_to_speech_playback_sample_rate": "Taxa de amostragem: {value}",
    "module_text_to_speech_playback_rate": "Taxa de reprodução: {value}",
    "module_text_to_speech_playback_audio_format": "Formato de áudio: PCM, 16 bits com sinal, mono",
    "module_text_to_speech_playback_speed": "Velocidade: {value}",
    "module_text_to_speech_playback_runtime": "Motor: {value}",
    "module_text_to_speech_dependency_required": "{value} necessário",
    "module_text_to_speech_status_ready": "Pronto para ler",
    "module_text_to_speech_status_stopped": "Parado.",
    "module_text_to_speech_status_finished": "Leitura concluída.",
    "module_text_to_speech_status_unavailable": "Voz indisponível.",
    "module_text_to_speech_status_empty": "Nada para ler.",
    "module_text_to_speech_status_loading": "Carregando modelo de voz…",
    "module_text_to_speech_status_preparing": "Preparando voz…",
    "module_text_to_speech_status_reading": "Lendo em voz alta…",
    "module_text_to_speech_status_paused": "Pausado.",
    "module_text_to_speech_error": "Erro: {error}",
    "module_text_to_speech_language_en": "Inglês",
    "module_text_to_speech_language_es": "Espanhol",
    "module_text_to_speech_language_de": "Alemão",
    "module_text_to_speech_language_fr": "Francês",
    "module_text_to_speech_language_it": "Italiano",
    "module_text_to_speech_language_vi": "Vietnamita",
    "module_text_to_speech_language_hi": "Hindi",
    "module_text_to_speech_language_zh": "Chinês (mandarim)",
    "module_text_to_speech_language_ja": "Japonês",
    "module_text_to_speech_language_runtime_required": "requer suporte do motor",
    "module_text_to_speech_error_note_locked": "Abra e desbloqueie esta nota antes de lê-la em voz alta.",
    "module_text_to_speech_error_read_note": "Não foi possível ler esta nota: {error}",
    "module_text_to_speech_action_read_from_cursor": "Ler em voz alta a partir do cursor",
}
