# Greek lexemes main_menu.py
lexemes = {
    "group_file_label": "Αρχείο",
    "group_edit_label": "Επεξεργασία",
    "group_tools_label": "Εργαλεία",
    "group_help_label": "Βοήθεια",

    "actions_file_label_new_document": "Νέο έγγραφο",
    "actions_file_accessible_name_new_document": "Νέο έγγραφο",
    "actions_file_label_open": "Άνοιγμα",
    "actions_file_accessible_name_open": "Άνοιγμα εγγράφου",
    "actions_file_label_save": "Αποθήκευση",
    "actions_file_accessible_name_save": "Αποθήκευση εγγράφου",
    "actions_file_label_save_as": "Αποθήκευση ως",
    "actions_file_accessible_name_save_as": "Αποθήκευση ως αντίγραφο εγγράφου",
    "actions_file_label_exit": "Έξοδος",
    "actions_file_accessible_name_exit": "Έξοδος από την εφαρμογή",

    "edit_actions_edit_mode": "Επεξεργασία",
    "edit_actions_accessible_name_edit_mode": "Επεξεργασία αρχείου",
    "edit_actions_source_mode": "Πηγαίος κώδικας",
    "edit_actions_accessible_name_source_mode": "Πηγαίος κώδικας",
    "edit_actions_bold": "Έντονα",
    "edit_actions_accessible_name_bold": "Μορφή έντονου κειμένου",
    "edit_actions_italic": "Πλάγια",
    "edit_actions_accessible_name_italic": "Μορφή πλάγιου κειμένου",
    "edit_actions_underline": "Υπογράμμιση",
    "edit_actions_accessible_name_underline": "Μορφή υπογεγραμμένου κειμένου",
    "edit_actions_strikethrough": "Διαγραμμίσεις",
    "edit_actions_accessible_name_strikethrough": "Μορφή διαγραμμισμένου κειμένου",
    "edit_actions_blockquote": "Παράθεση",
    "edit_actions_accessible_name_blockquote": "Μορφή κειμένου παράθεσης",

    "tools_actions_ai_assistant": "Βοηθός AI",
    "tools_actions_accessible_name_ai_assistant": "Εκκίνηση Βοηθού AI",
    "tools_actions_color_picker": "Επιλογέας χρώματος",
    "tools_actions_accessible_name_color_picker": "Επιλέξτε χρώμα κειμένου",

    "actions_help_label_md_syntax": "Σύνταξη Markdown",
    "actions_help_accessible_name_md_syntax": "Σύνταξη Markdown",
    "actions_help_label_check_for_updates": "Έλεγχος για ενημερώσεις",
    "actions_help_accessible_name_check_for_updates": "Έλεγχος για ενημερώσεις",
    "actions_help_label_bug_report": "Αναφορά σφαλμάτων",
    "actions_help_accessible_name_bug_report": "Υποβολή αναφοράς σφάλματος",
    "actions_help_label_about": "Πληροφορίες",
    "actions_help_accessible_name_about": "Πληροφορίες",
}
