# Japanese lexemes common.py
lexemes = {
    "module_text_to_speech_name": "テキスト読み上げ",
    "module_text_to_speech_action_read_selection": "選択範囲を読み上げる",
    "module_text_to_speech_action_read_file": "ファイルを読み上げる",
    "module_text_to_speech_action_read": "読み上げる",
    "module_text_to_speech_action_read_document": "文書を読み上げる",
    "module_text_to_speech_action_pause_resume": "一時停止／再開",
    "module_text_to_speech_action_stop": "読み上げを停止",
    "module_text_to_speech_playback_details": "再生の詳細",
    "module_text_to_speech_model_not_loaded": "未読み込み",
    "module_text_to_speech_playback_model": "モデル：{value}",
    "module_text_to_speech_playback_codec": "コーデックモデル：{value}",
    "module_text_to_speech_playback_voice": "音声：{value}",
    "module_text_to_speech_playback_language": "言語：{value}",
    "module_text_to_speech_playback_sample_rate": "サンプルレート：{value}",
    "module_text_to_speech_playback_rate": "再生レート：{value}",
    "module_text_to_speech_playback_audio_format": "音声形式：PCM、符号付き16ビット、モノラル",
    "module_text_to_speech_playback_speed": "速度：{value}",
    "module_text_to_speech_playback_runtime": "ランタイム：{value}",
    "module_text_to_speech_dependency_required": "{value} が必要です",
    "module_text_to_speech_status_ready": "読み上げ準備完了",
    "module_text_to_speech_status_stopped": "停止しました。",
    "module_text_to_speech_status_finished": "読み上げが完了しました。",
    "module_text_to_speech_status_unavailable": "音声を利用できません。",
    "module_text_to_speech_status_empty": "読み上げる内容がありません。",
    "module_text_to_speech_status_loading": "音声モデルを読み込み中…",
    "module_text_to_speech_status_preparing": "音声を準備中…",
    "module_text_to_speech_status_reading": "読み上げ中…",
    "module_text_to_speech_status_paused": "一時停止中。",
    "module_text_to_speech_error": "エラー：{error}",
    "module_text_to_speech_language_en": "英語",
    "module_text_to_speech_language_es": "スペイン語",
    "module_text_to_speech_language_de": "ドイツ語",
    "module_text_to_speech_language_fr": "フランス語",
    "module_text_to_speech_language_it": "イタリア語",
    "module_text_to_speech_language_vi": "ベトナム語",
    "module_text_to_speech_language_hi": "ヒンディー語",
    "module_text_to_speech_language_zh": "中国語（標準語）",
    "module_text_to_speech_language_ja": "日本語",
    "module_text_to_speech_language_runtime_required": "ランタイムの対応が必要",
    "module_text_to_speech_error_note_locked": "読み上げる前に、このノートを開いてロックを解除してください。",
    "module_text_to_speech_error_read_note": "このノートを読み込めません：{error}",
    "module_text_to_speech_action_read_from_cursor": "カーソル位置から読み上げる",
}
