# Spanish lexemes common.py
lexemes = {
    "module_text_to_speech_name": "Texto a voz",
    "module_text_to_speech_action_read_selection": "Leer selección en voz alta",
    "module_text_to_speech_action_read_file": "Leer archivo en voz alta",
    "module_text_to_speech_action_read": "Leer en voz alta",
    "module_text_to_speech_action_read_document": "Leer documento en voz alta",
    "module_text_to_speech_action_pause_resume": "Pausar / Reanudar",
    "module_text_to_speech_action_stop": "Detener lectura",
    "module_text_to_speech_playback_details": "Detalles de reproducción",
    "module_text_to_speech_model_not_loaded": "Sin cargar",
    "module_text_to_speech_playback_model": "Modelo: {value}",
    "module_text_to_speech_playback_codec": "Modelo de códec: {value}",
    "module_text_to_speech_playback_voice": "Voz: {value}",
    "module_text_to_speech_playback_language": "Idioma: {value}",
    "module_text_to_speech_playback_sample_rate": "Frecuencia de muestreo: {value}",
    "module_text_to_speech_playback_rate": "Frecuencia de reproducción: {value}",
    "module_text_to_speech_playback_audio_format": "Formato de audio: PCM, 16 bits con signo, mono",
    "module_text_to_speech_playback_speed": "Velocidad: {value}",
    "module_text_to_speech_playback_runtime": "Motor: {value}",
    "module_text_to_speech_dependency_required": "Se requiere {value}",
    "module_text_to_speech_status_ready": "Listo para leer",
    "module_text_to_speech_status_stopped": "Detenido.",
    "module_text_to_speech_status_finished": "Lectura finalizada.",
    "module_text_to_speech_status_unavailable": "Voz no disponible.",
    "module_text_to_speech_status_empty": "No hay nada que leer.",
    "module_text_to_speech_status_loading": "Cargando modelo de voz…",
    "module_text_to_speech_status_preparing": "Preparando voz…",
    "module_text_to_speech_status_reading": "Leyendo en voz alta…",
    "module_text_to_speech_status_paused": "En pausa.",
    "module_text_to_speech_error": "Error: {error}",
    "module_text_to_speech_language_en": "Inglés",
    "module_text_to_speech_language_es": "Español",
    "module_text_to_speech_language_de": "Alemán",
    "module_text_to_speech_language_fr": "Francés",
    "module_text_to_speech_language_it": "Italiano",
    "module_text_to_speech_language_vi": "Vietnamita",
    "module_text_to_speech_language_hi": "Hindi",
    "module_text_to_speech_language_zh": "Chino (mandarín)",
    "module_text_to_speech_language_ja": "Japonés",
    "module_text_to_speech_language_runtime_required": "requiere soporte del motor",
    "module_text_to_speech_error_note_locked": "Abre y desbloquea esta nota antes de leerla en voz alta.",
    "module_text_to_speech_error_read_note": "No se puede leer esta nota: {error}",
    "module_text_to_speech_action_read_from_cursor": "Leer en voz alta desde el cursor",
}
